### ISSUE TITLE
Design a new footer

### ISSUE THREAD

**Issue by pankajkumarbij** [pankajkumarbij/easy-job-intern#10]
Design a new footer for the website

**Comment by abhinav5481** [comment]
Hi Pankaj,
I would like to work on this issue, could you please assign this to me?

**Comment by Devenkapoor7303** [comment]
Can I work on this issue

**Comment by pankajkumarbij** [comment]
> Hi Pankaj,
> I would like to work on this issue, could you please assign this to me?
@abhinav5481 Go ahead
