### ISSUE TITLE
Adding security features - gssoc'21

### ISSUE THREAD

**Issue by krishna-y2000** [pankajkumarbij/easy-job-intern#103]
## Is your feature request related to a problem? Please describe.
Improves the security of the website.

## Describe the solution you'd like
Setting various HTTP headers using helmet
Rate limiter so the server won't get overload.
Added mongo sanitize for data sanitization against noSQL query injection
Added xss for data sanitization against XSS.

I have also worked on this before on another gssoc project with level 2 tag .  If you find it relevant, please assign me.

I am a GSSOC'21 participant.

**Comment by krishna-y2000** [comment]
@pankajkumarbij  hii , 
I would like to work this issue . please assign this to me .

**Comment by pankajkumarbij** [comment]
@krishna-y2000 Actually first we are adding features and basic work so we will work on improving the website later.

You can suggest any other feature request and tell me in the suggestion issue I will discuss it with you there.
we do not need it at this time.

Thanks for opening this issue.
