### ISSUE TITLE
Add a 'Saved items' section

### ISSUE THREAD

**Issue by SananditaDas** [pankajkumarbij/easy-job-intern#104]
I intend to add a 'saved items' section beside the blogs section, and design the page as well.
On clicking it,
- If the user is not signed in, it will redirect to signup/login page
- Else, show the saved items page

@pankajkumarbij can you please assign me this issue as a part of GSSOC'21?

**Comment by pankajkumarbij** [comment]
@SananditaDas Till now in the project there are no such items.
Can you explain more about it what you are going to implement

**Comment by SananditaDas** [comment]
> @SananditaDas Till now in the project there are no such items.
> Can you explain more about it what you are going to implement

I am going to design a separate page to display the particular jobs the user has saved to view it later sometime.

Implementation - 
In the main database, each user will have a unique id, and each unique id will be associated with an array of saved items. So while displaying those saved items (for the current user) we just need to filter by his unique id and load the items in the webpage. Here the 'items' are those each individual jobs/internships available in the website.
I will be using Node and React.

**Comment by pankajkumarbij** [comment]
@SananditaDas First we have to develop the website more because till now there are no job items so the user can save the items.

So we will do it later.

**Comment by SananditaDas** [comment]
> @SananditaDas First we have to develop the website more because till now there are no job items so the user can save the items.
> 
> So we will do it later.

Ok
