### ISSUE TITLE
Signup Verification

### ISSUE THREAD

**Issue by krishna-y2000** [pankajkumarbij/easy-job-intern#106]
## Is your feature request related to a problem? Please describe.
I found out that one can register any dummy email which is not in even real world. So, its necessary to verify the email for properly validate the user.

## Describe the solution you'd like
I would add signup verificaion through email feature .

Please assign this issue to me as part of GSSOC'21 and apply tag level to it .

**Comment by pankajkumarbij** [comment]
@krishna-y2000 Go ahead

**Comment by krishna-y2000** [comment]
Hii @pankajkumarbij  sir ,
Sir is there anyone who can help me out. I am new to it and facing problem .I tried to ask few people in general channel but could not get appropriate answer.

**Comment by pankajkumarbij** [comment]
@krishna-y2000 We have to use email verifier api to validate the correct email. If you are not able to do it then no problem we don't need this feature this time.

**Comment by krishna-y2000** [comment]
@pankajkumarbij  , yes sir i know that. But i am not able to do it that with react-hooks. I can do that in backend part of nodejs.

**Comment by pankajkumarbij** [comment]
@krishna-y2000 Ok, then no problem we need it only for the front end part if you can not do we will do it later.

**Comment by krishna-y2000** [comment]
@pankajkumarbij  ok sir , even though i will try this and let this issue be open .

**Comment by pankajkumarbij** [comment]
@krishna-y2000 ok

I am in my 3rd year so please don't call me sir.

**Comment by Jassi10000-zz** [comment]
@pankajkumarbij Being a GSSOC'21 participant , I also want to  try my hands out on this issue , can you pls assign me this

**Comment by krishna-y2000** [comment]
Hii @Jassi10000 ,
I am the assigned person. But would you like to work with me . You will do react part and i will do the backend . What do you say ? 
@pankajkumarbij you can divide our points on leaderboard, right ? I asked in general channel we can divide it.

**Comment by pankajkumarbij** [comment]
@Jassi10000 can you work with @krishna-y2000 ?

**Comment by Jassi10000** [comment]
Sure @pankajkumarbij   , I am ready to work with @krishna-y2000 . I will work for frontend form validations and he can take for backend

**Comment by pankajkumarbij** [comment]
@krishna-y2000 Ok If you are not able to do it no problem we have not need this feature this time.
Thanks

**Comment by krishna-y2000** [comment]
@pankajkumarbij hii, 
Actually, i have texted few people to discuss on this problem because i want to complete this backend and frontend completely. If you want this urgently then I  can send the pr in 2 days of backend . Then you can raise issue for frontend .I hope it would be good idea . So, please reopen this i will send pr in 2 days

**Comment by pankajkumarbij** [comment]
@krishna-y2000 No problem If you are trying then try to give PR for both backend and frontend both.
I have not needed it urgently but other PR related to frontend and backend so you should pull all the changes first and implement accordingly.

Pull all the changes first from the original repo.

Take time and implement for both frontend and backend both.

**Comment by CMELAKKIA** [comment]
@pankajkumarbij  hi i would like to help @krishna-y2000  with the frontend part if required.

**Comment by krishna-y2000** [comment]
> @pankajkumarbij hi i would like to help @krishna-y2000 with the frontend part if required.

@CMELAKKIA thanks for your help but i have found the way to do this. Currently exams are going on so out for few days. I will definitely approach you if needed. Ping me at ```kyadav#6342``` on discord.

**Comment by pankajkumarbij** [comment]
@CMELAKKIA Go ahead with @krishna-y2000

**Comment by krishna-y2000** [comment]
> @CMELAKKIA Go ahead with @krishna-y2000

@pankajkumarbij  He will not get the points in leaderboard here because 1PR = 1 Person point rule . As i told , if i will face any difficulty then i will approach him and tell him to make another issue for frontend then we will sync both . So , its no use to assign him . 

My progress : made 60% of backend code and will complete fully in few days after my exams .Thanks.

**Comment by pankajkumarbij** [comment]
ok

**Comment by Ankita297** [comment]
@pankajkumarbij  Can we use firebase for this ?

**Comment by Ankita297** [comment]
If yes then  i want to work on this ?

**Comment by krishna-y2000** [comment]
@pankajkumarbij hii,
My progress : I have completed the verification for student part successfully . Now i am doing for employer . It will be completed soon.
