### ISSUE TITLE
Add logo to the navbar

### ISSUE THREAD

**Issue by krishnmohan19** [pankajkumarbij/easy-job-intern#108]
## Is your feature request related to a problem? Please describe.
its better to have logo on navbar.Improve UI

## Describe the solution you'd like
Adding a logo ,make Navbar more attractive .

**Comment by krishnmohan19** [comment]
I would like to add logo  on navbar.
Please assign this issue to me as part of GSSOC'21 and apply tag level to it .

**Comment by pankajkumarbij** [comment]
@krishnmohan19 Go ahead

Design a logo and fir it into the navbar. The logo should not be very large and change the height of the navbar.

**Comment by krishnmohan19** [comment]
Hey, @pankajkumarbij 
I have made a PR for this issue. Please review it.
https://github.com/pankajkumarbij/easy-job-intern/pull/126

**Comment by pankajkumarbij** [comment]
@krishnmohan19 any update??

**Comment by pankajkumarbij** [comment]
@krishnmohan19  any update??
