### ISSUE TITLE
Suggestion: Create a Slider in Main Section (Home)

### ISSUE THREAD

**Issue by WebVishal** [pankajkumarbij/easy-job-intern#109]
Hii @pankajkumarbij  I'm Vishal Kumar, I want to contribute to this project as participant Gssoc21 when I reviewed this website then I realized that I think should be a slider in the main section for more interactive user Can I work on it if yes then please assigned this issue to me

**Comment by pankajkumarbij** [comment]
@WebVishal Go ahead
