### ISSUE TITLE
Add a single command to run server with client together.

### ISSUE THREAD

**Issue by pankajkumarbij** [pankajkumarbij/easy-job-intern#11]
Currently, we need to start the server inside the server directory using ```nodemon or node app.js``` and start the client using ```npm start```. We want a single command ```npm start``` which should start both the server and the client.

**Comment by Devenkapoor7303** [comment]
can i work on this issue

**Comment by pankajkumarbij** [comment]
@Devenkapoor7303 Go ahead.

Make sure the project structure should not change.

**Comment by Devenkapoor7303** [comment]
Okay
