### ISSUE TITLE
No need to use body-parser when using express version 4.16+

### ISSUE THREAD

**Issue by abhay27chauhan** [pankajkumarbij/easy-job-intern#111]
## Is your feature request related to a problem? Please describe.
Express version 4.16+, their own body-parser implementation is now included in the default Express package so there is no need for you to download another dependency.

## Describe the solution you'd like
You have added a line to your code that looks like the following:

- app.use(bodyparser.json()); 

If you are using Express 4.16+ you can now replace that line with:

- **app.use(express.json());** 

you also have the following code in your environment:

- app.use(bodyParser.urlencoded({extended: true}));

You can replace that with:

- **app.use(express.urlencoded());**

**Comment by pankajkumarbij** [comment]
@abhay27chauhan This issue is already open in issue #105.
He is given PR also so now issue is solve.
I am closing this issue.
