### ISSUE TITLE
I want to improve Size of the text "Easy Job intern" in navbar

### ISSUE THREAD

**Issue by NehaK745** [pankajkumarbij/easy-job-intern#113]
## Is your feature request related to a problem? Please describe.
I think lt will look better if the size of the text will be bigger than another link.

## Describe the solution you'd like
Increasing font size makes it look better.

## Additional context
Please assign this issue to me as part of GSSOC'21.

**Comment by pankajkumarbij** [comment]
@NehaK745 Thanks for opening an issue but we do not need of brand name in the navbar because we need a logo instead of that so that issue is already assigned to someone.
