### ISSUE TITLE
Creating an Employee Model

### ISSUE THREAD

**Issue by hrushikesh-git** [pankajkumarbij/easy-job-intern#114]
![employe](https://user-images.githubusercontent.com/65762074/111518669-4ba91a00-877c-11eb-8ae9-0efbacbae899.png)
As mentioned on the website we have a signing and Register links for the employee so we can Create a MongoDB model of the employee.
Schema Overview

- Name of Employee
- Official Mail
- password
- Company/Firm Name
- Job Title available for internship

and we can work on more of it
if you consider these issues please assign this to me I will work on it

**Comment by pankajkumarbij** [comment]
@hrushikesh-git Thanks for opening an issue but this issue is already assigned to someone because he designs the frontend part and wants backend work for the same under another program.
