### ISSUE TITLE
Integrate Employer signup & login data with backend

### ISSUE THREAD

**Issue by abhinav5481** [pankajkumarbij/easy-job-intern#117]
## Is your feature request related to a problem? Please describe.
Yes. Integrate Employer signup & login data with backend

Also, solve problems related to data is not stored for login and signup form of students.

**Comment by abhinav5481** [comment]
Hi @pankajkumarbij 
I would like to work on this as part of CrossWoc'21. Please assign it to me.

**Comment by pankajkumarbij** [comment]
@abhinav5481 Go ahead

and also login and signup for student's backend are already present so you should manage both and write a similar code format.

Currently login and signup for students data not stored after merged some PR. please check if any mistake you found.

I give this issue label hard.

You can open an issue for student login and signup form improvement for students and make a similar design to the employer form.

**Comment by pankajkumarbij** [comment]
@abhinav5481 are you working on it?

**Comment by abhinav5481** [comment]
Yeah I have almost completed it. I will create PR by today

**Comment by abhinav5481** [comment]
Will that be fine?

**Comment by pankajkumarbij** [comment]
@abhinav5481 ok ok, you can take time to implement I want only confirm about it.
