### ISSUE TITLE
Improve the design of Student login & Student Signup page

### ISSUE THREAD

**Issue by abhinav5481** [pankajkumarbij/easy-job-intern#118]
## Describe the bug
The design of the Student signup page at this point of time is way different from the rest of the application which is affecting the 
aesthetics of the application.

## Expected behaviour
The student Signup page should have a good aesthetic appeal aligned with the rest of the design of the application.

**Comment by abhinav5481** [comment]
Hi @pankajkumarbij 
I would like to work on it as part of crossWoc'21. Please assign it to me.

**Comment by pankajkumarbij** [comment]
@abhinav5481 Go ahead
