### ISSUE TITLE
Design a sign up and sign in form.

### ISSUE THREAD

**Issue by pankajkumarbij** [pankajkumarbij/easy-job-intern#12]
Design a sign-up page with basic details with react and react-bootstrap.
Name, Email, Mobile no, password, confirm password, image, college name, etc.

Sign-in form only with email and password.

**Comment by arbazalam01** [comment]
Can i work on this issue

**Comment by pankajkumarbij** [comment]
@arbazalam01 Go ahead

**Comment by arbazalam01** [comment]
Thanks for assigning me
