### ISSUE TITLE
Category in Internships

### ISSUE THREAD

**Issue by hrushikesh-git** [pankajkumarbij/easy-job-intern#120]
I have and Idea to Introduce the categories in this platform, as there are many fields for internship and many of us are sure about the category and domain in which we have to do internships so we can introduce a  category(Modal ) which then we can help to sort and internships and the user will have a good user experience with it.

@pankajkumarbij  Please look into this and let me know what you think and assign it to me if you agree

**Comment by pankajkumarbij** [comment]
@hrushikesh-git Go ahead.

**Comment by hrushikesh-git** [comment]
Thank You!
Hey Will You help me? How should I update my local repository with all changes in the current repo ?

**Comment by pankajkumarbij** [comment]
> Thank You!
> Hey Will You help me? How should I update my local repository with all changes in the current repo ?

@hrushikesh-git You have to pull all the changes from the original repo master branch.

Read the official documentation for how to pull all the changes from the original repo or you can take the help of other internet resources to learn.

**Comment by hrushikesh-git** [comment]
Thank You

**Comment by hrushikesh-git** [comment]
Thank You
