### ISSUE TITLE
Add Fresher Jobs alongside Internship

### ISSUE THREAD

**Issue by sk1122** [pankajkumarbij/easy-job-intern#121]
## Is your feature request related to a problem? Please describe.

Getting a Job as a Fresher is more tough that to get an Internship.
To make available opportunities for jobs also we would help a lot of people out there.

## Describe the solution you'd like

I think we can add another section "Fresher Jobs" which will only have full time offers.
When adding a job we can let the user select what he want to add an internship or a job.

## Additional context
Add any other context about the feature request here.

I would love to work and collaborate on this.

**Comment by pankajkumarbij** [comment]
@sk1122 There is already an option for the fresher's job in the navbar.

On which part you want to work please describe and how?

**Comment by sk1122** [comment]
Oh Sorry, have you deployed your website cause I can't see the link

**Comment by pankajkumarbij** [comment]
@sk1122 Project is not deployed but you can see by the run project in your local system.

After checking everything then you can open the best issue.
