### ISSUE TITLE
UI of Student -Register Form

### ISSUE THREAD

**Issue by nikitakapoor1919** [pankajkumarbij/easy-job-intern#123]
## Is your feature request related to a problem? Please describe.
I want to change UI of student signup form
## Describe the solution you'd like
![Untitled](https://user-images.githubusercontent.com/62166533/111683494-934aa700-884b-11eb-96a5-75e817bc4b4f.png)
I have notice confirm password is of type="text" but it must be type="password"
Also I want to make UI enhancement here.

## Additional context
Please assign me this task under GGSOC participant

**Comment by pankajkumarbij** [comment]
@nikitakapoor1919 Go ahead and make type="password" for confirm password and type=" number" for contact field in all 4 forms login, signup for student and employer.

**Comment by pankajkumarbij** [comment]
@nikitakapoor1919 are you working on it?

Any update?

**Comment by nikitakapoor1919** [comment]
@pankajkumarbij Yes I have update types U have mentioned. Shall I update UI also ?

**Comment by pankajkumarbij** [comment]
@nikitakapoor1919 We only need to chnage types at this time.

But if you have a better UI then send me some sample screenshots I will review and tell you.

Now one PR related to signup signing is merged so pull all the changes from original repo.

**Comment by nikitakapoor1919** [comment]
@pankajkumarbij  I will do that.
And I will send some UI design ideas also which I am thinking.
