### ISSUE TITLE
Making the login and signup form UI mobile responsive

### ISSUE THREAD

**Issue by kartikpuri99** [pankajkumarbij/easy-job-intern#125]
## Is your feature request related to a problem? Please describe.
Right now the signup and login form are not mobile responsive.It is looking something like this in mobile view.

![image](https://user-images.githubusercontent.com/52126579/111740415-bf494500-88aa-11eb-8aab-166f4c846ad3.png)

## Describe the solution you'd like
Instead it should be take the full width in mobile view like this.(Just an example)

![image](https://user-images.githubusercontent.com/52126579/111741123-f4a26280-88ab-11eb-99c5-f511a13c1f39.png)

Please assign this issue to me and let me fix this.

**Comment by pankajkumarbij** [comment]
@kartikpuri99 Go ahead.

**Comment by kartikpuri99** [comment]
Also i have just checked the code and noticed that someone has removed all the signup and login form logic and form validations in the frontend part.

**Comment by pankajkumarbij** [comment]
@kartikpuri99 Yeah I have merged by mistake by just looking at screenshots without checking file different code.

Can you please do it again because you have done those things I think you have all the logic?

If you can do then please do it.

**Comment by kartikpuri99** [comment]
I have to check it if i am having those codes .if i am having it i will do it .Let me check it first.

**Comment by pankajkumarbij** [comment]
ok

**Comment by kartikpuri99** [comment]
Okay I am having it i will make all the required changes.

**Comment by pankajkumarbij** [comment]
ok

**Comment by kartikpuri99** [comment]
@pankajkumarbij  I have submitted the PR  with all the changes you requested please review it.
