### ISSUE TITLE
Models and Routes for companies

### ISSUE THREAD

**Issue by chauhanprakhar** [pankajkumarbij/easy-job-intern#127]
I think it would be great if companies have their models where they can easily see the no. of applicants and their responses from which they can view their profiles. This will also give the flexibility to create a profile section for companies as well. A company will post intern if we will give them more options and features. I would like you to think about this idea and please give me suggestions too what features a company expects. If you like this idea please assign me otherwise we can discuss other possibilities.

**Comment by pankajkumarbij** [comment]
@chauhanprakhar Wait for some time because some backend part is ongoing after that we will discuss it and I will assign some work to you related to it.

**Comment by chauhanprakhar** [comment]
@pankajkumarbij  so it's discussed now

**Comment by pankajkumarbij** [comment]
@chauhanprakhar Now log-in and Signup page for employers are working fine.

After login an employer there should be shows in the navbar email of the employer, and a dropdown with view profile, edit profile, open an opportunity, and a logout button.

After login an employer if he clicks on view profile then they should able to view all the details about them except password.

Can you do this task?

**Comment by chauhanprakhar** [comment]
@pankajkumarbij  okay, I will add this logic in the backend.

**Comment by pankajkumarbij** [comment]
@chauhanprakhar Need in both backend and frontend both.

**Comment by aishwarya0816** [comment]
@pankajkumarbij I would like to do the frontend for it while he does the logic in backend

**Comment by pankajkumarbij** [comment]
@aishwarya0816 You do the frontend part and @chauhanprakhar You can do the backend part.

please tell me it is ok for you both?

If you need any more clear information about it then please let me know here.

**Comment by aishwarya0816** [comment]
Yes @pankajkumarbij this looks good to me. Will you be suggesting the design for it that matches with the rest of the website ? 
Also @chauhanprakhar ,
(Aishwarya (P)) is my discord username in case we need to discuss anything regarding this issue

**Comment by pankajkumarbij** [comment]
@aishwarya0816 @chauhanprakhar please open new issues with a clear description regarding your work.
