### ISSUE TITLE
Validation Improvement in Signup Form

### ISSUE THREAD

**Issue by Jassi10000-zz** [pankajkumarbij/easy-job-intern#128]
## Is your feature request related to a problem? Please describe.
I currently forked this repo and tried to signup in the signup form seciton with some random wrong details [ name , password , contact  etc . ]  and as a result it got submitted which is wrong for the project 

here's the demo 
![githubissue](https://user-images.githubusercontent.com/64856348/111862944-795db100-897e-11eb-8687-2a1bc881814a.PNG)

## Describe the solution you'd like
Being a GSSOC'21 Participant , I am interested to work and improve this project by adding some great validations . @pankajkumarbij  Can you please assign this to me with   " GSSOC "   and associated " Level "  Label  , so that I can start working on it to give best outcome

## Additional context
Add any other context about the feature request here.
No

**Comment by pankajkumarbij** [comment]
@Jassi10000 Go ahead and make validation for all 4 sign-up and login pages for students and employers.
I give level3 if you do validation for all pages.

**Comment by Jassi10000** [comment]
> @Jassi10000 Go ahead and make validation for all 4 sign-up and login pages for students and employers.
> I give level3 if you do validation for all pages.

Thanks @pankajkumarbij   , sure I'll try my best to deliver best result

**Comment by Jassi10000-zz** [comment]
Sure @pankajkumarbij  , I will try my best to do that with expected outcome , thanks for assigning me 

Sir I have to ask one thing , can you please how many of them are for frontend and how for backend ? 
so pls add the tags for that too

**Comment by pankajkumarbij** [comment]
@Jassi10000 Bro there are no points for frontend and backend tags.

Points depend upon level tags only.

Level0<Level1<Level2<Level3

**Comment by Jassi10000-zz** [comment]
Okk sure brother @pankajkumarbij  , thanks for clearing

**Comment by akshay1027** [comment]
I would like to contribute to this issue as well, if it's still open after some days, please assign me

**Comment by pankajkumarbij** [comment]
@akshay1027 this issue is opened tomorrow only.

**Comment by pankajkumarbij** [comment]
@Jassi10000 Pull all the changes from an original branch before making a pull request because there are some pull requests merged.

**Comment by Jassi10000-zz** [comment]
@pankajkumarbij you mean I must  " git pull " all the changes in my forked version  before  adding some new code ?

If this is you are saying , then that I have already done

**Comment by pankajkumarbij** [comment]
> @pankajkumarbij you mean I must " git pull " all the changes in my forked version before adding some new code ?
> 
> If this is you are saying , then that I have already done

Ok then work on it

**Comment by Jassi10000** [comment]
Sir am available between 4-5

**Comment by pankajkumarbij** [comment]
@Jassi10000 Any update?

**Comment by Jassi10000-zz** [comment]
Yeah 70% work done , actually I was preparing for an exam , that's why was engaged in that for 4 days
I will try to send the PR as soon as possible with best changes asked

**Comment by pankajkumarbij** [comment]
@Jassi10000 No problem I have not need to do it urgently.

Take time to prepare for the exam first and after finish the exams complete the work.

Thanks

**Comment by Jassi10000-zz** [comment]
@pankajkumarbij Thanks brother  so much for understanding , but no issues am done with my preparation , will deliver the PR latest by tomorrow
