### ISSUE TITLE
add contributing.md file

### ISSUE THREAD

**Issue by pankajkumarbij** [pankajkumarbij/easy-job-intern#13]
Use some screenshots for better understanding in contributing file.

**Comment by 96RadhikaJadhav** [comment]
@pankajkumarbij Can I work on it?

**Comment by pankajkumarbij** [comment]
> @pankajkumarbij Can I work on it?

Are you part of any open-source program?

**Comment by 96RadhikaJadhav** [comment]
> > @pankajkumarbij Can I work on it?
> 
> Are you part of any open-source program?

Yes. I'm a participant of CrossWoc.

**Comment by pankajkumarbij** [comment]
@96RadhikaJadhav go ahead

**Comment by pankajkumarbij** [comment]
@96RadhikaJadhav are you working on this issue?

**Comment by arbazalam01** [comment]
Can i work on this issue

**Comment by pankajkumarbij** [comment]
@arbazalam01 Go ahead
