### ISSUE TITLE
Clutter Free Routes(Moving to Controllers) 

### ISSUE THREAD

**Issue by hrushikesh-git** [pankajkumarbij/easy-job-intern#130]
To much clutter inside the router files, We can Move the functions in the controller files and that will reduce the clutter in routes folder and that will be more traceable we will follow the MCV architecture Model–view–controller, so we will introduce the controller folder in the backend
 
![MVC](https://user-images.githubusercontent.com/65762074/111871330-5992b100-89af-11eb-813f-2f39a1b99aef.png)

![controller example](https://user-images.githubusercontent.com/65762074/111871335-5dbece80-89af-11eb-8173-80f7b9e8c9d2.png)

If you find this useful then please assign this issue to me

**Comment by pankajkumarbij** [comment]
@hrushikesh-git at this time we don't need this feature.

Thanks

**Comment by hrushikesh-git** [comment]
okay thanks anyway
