### ISSUE TITLE
Betterment of the PR template

### ISSUE THREAD

**Issue by aishwarya0816** [pankajkumarbij/easy-job-intern#135]
## Is your feature request related to a problem? Please describe.
The current PR template does not suggest the contributor to add necessary screenshots.

## Describe the solution you'd like
I will add the mentioned section in template for original and updated template

Please assign it to me @pankajkumarbij

**Comment by pankajkumarbij** [comment]
@aishwarya0816 Go ahead and add a screenshot/video section in the PR template.
