### ISSUE TITLE
Adding form validation in employer SignIn and login form and making it mobile responsive

### ISSUE THREAD

**Issue by kartikpuri99** [pankajkumarbij/easy-job-intern#139]
## Is your feature request related to a problem? Please describe.
Right now there are no form validation in employer SignIn and login form and is not mobile responsive

## Describe the solution you'd like
I want to resolve this issue and want to add form validation into it.Kindly assign this issue to me

**Comment by pankajkumarbij** [comment]
@kartikpuri99 please don't add validation for this because one issue is already opened for it.

you have to need only to make the page responsive only for employers.

**Comment by kartikpuri99** [comment]
okay i will remove the validation part of the code for employer

**Comment by pankajkumarbij** [comment]
@kartikpuri99 ok remove validation only for the employer, not for students.
