### ISSUE TITLE
Design an about us page.

### ISSUE THREAD

**Issue by pankajkumarbij** [pankajkumarbij/easy-job-intern#14]
Design an about us page with react-bootstrap.

**Comment by arbazalam01** [comment]
Can i work on this task.

**Comment by pankajkumarbij** [comment]
> Can i work on this task.

@arbazalam01 You can work on one issue at a time.

**Comment by soumya-badkul** [comment]
@pankajkumarbij I would like to work on this issue

**Comment by pankajkumarbij** [comment]
> @pankajkumarbij I would like to work on this issue

Go ahead.
