### ISSUE TITLE
Need controller folder

### ISSUE THREAD

**Issue by himanshujaidka** [pankajkumarbij/easy-job-intern#142]
## Describe the bug
Route file should be clear and there is a need for a controller folder and inside the controller, all the logic should be present
I will be happy, if this issue is assigned to me

**Comment by himanshujaidka** [comment]
@pankajkumarbij any updates?

**Comment by pankajkumarbij** [comment]
@himanshujaidka Ok go ahead but after changing all the files and logics in the controller folder and route folder sign and login should work for both students and employers.

**Comment by himanshujaidka** [comment]
okay, working
