### ISSUE TITLE
Logout route

### ISSUE THREAD

**Issue by mitalirs** [pankajkumarbij/easy-job-intern#144]
## Solution
I will create these (logout from current session + logout from all sessions) routes for both student and employer inside the respective router files. User authentication will be a pre-requisite to perform this operation. So it will make use of auth middleware.

@pankajkumarbij, can you please assign this issue to me? I am a participant in the GSSoC'21 program.

**Comment by pankajkumarbij** [comment]
@mitalirs please add a logout button in the navbar after login a student or employer connect with the backend.

**Comment by mitalirs** [comment]
I am really sorry @pankajkumarbij. I am still working on reactjs because I am also having my semester exams. Could I please add the backend logic only? I will specify the details in the PR

**Comment by pankajkumarbij** [comment]
@mitalirs ok write backend code only and give details.

**Comment by mitalirs** [comment]
@pankajkumarbij I have created the Pull Request. Please review it.
