### ISSUE TITLE
Frontend for 'Your Profile' page of employer.

### ISSUE THREAD

**Issue by aishwarya0816** [pankajkumarbij/easy-job-intern#147]
After login by an employer the navbar should show the  email of the employer, and a dropdown with view profile, edit profile, open an opportunity, and a logout button. 

@pankajkumarbij Please assign me this issue as discussed earlier.

**Comment by pankajkumarbij** [comment]
@aishwarya0816 Go ahead

**Comment by pankajkumarbij** [comment]
@aishwarya0816 Now the PR related to Logout logic in the backend is merged you can now easily implement the logout part.

**Comment by aishwarya0816** [comment]
@pankajkumarbij okay! 👍
Is it possible to make this a level 3 issue?

**Comment by pankajkumarbij** [comment]
@aishwarya0816 After making the PR I will update labels according to your work.

**Comment by pankajkumarbij** [comment]
@aishwarya0816 any update?

**Comment by aishwarya0816** [comment]
@pankajkumarbij working on it. I had an exam so this got delayed

**Comment by pankajkumarbij** [comment]
> @pankajkumarbij working on it. I had an exam so this got delayed

@aishwarya0816 Ok prepare for the exam first and after that work on it.

**Comment by pankajkumarbij** [comment]
@aishwarya0816 Any update?
