### ISSUE TITLE
Separate functions in user model + token generation

### ISSUE THREAD

**Issue by mitalirs** [pankajkumarbij/easy-job-intern#150]
## Separate functions in user model + token generation on signup

1. I will create separate functions in the model files of employer and student to: 
a. generate auth tokens
b. find the user by credentials
c. hash password before it gets saved to the database
instead of writing the code in the routes directly as this will increase the code reusability.
2. Currently, a token is not being generated when an employer is signing up. I will add the code so that token gets generated and saved to the tokens array

@pankajkumarbij, can you please assign this issue to me? I am a participant in the GSSoC'21 program.

**Comment by pankajkumarbij** [comment]
@mitalirs Wait I will confirm with you when you should start work on it.

Because after merged one backend PR related to the controller folder you can work for login token generation etc.

But you have to update the front end also after changing the backend code means after changing the code login and signup for students and employers both should work.

**Comment by mitalirs** [comment]
So I can start working once the controller folder related PR gets merged, right?

**Comment by pankajkumarbij** [comment]
@mitalirs Token is generating in when a student or employer login checks once in the controller backend that part is already done.

**Comment by mitalirs** [comment]
No I am telling about the case when user is signing up for the first time and not the login route

**Comment by pankajkumarbij** [comment]
@mitalirs Can you please explain why we need token when sign up.

**Comment by mitalirs** [comment]
if a user visits the site for the first time he/she will use signup route, a token should get generated because that can also be treated as a session, if he/she wishes to logout during that session we will need the token to ensure that he/she gets logged out

**Comment by pankajkumarbij** [comment]
@mitalirs Go ahead.

**Comment by pankajkumarbij** [comment]
@mitalirs Password is already hashing.

**Comment by mitalirs** [comment]
Password must be hashed before it gets saved to the database (if it is modified). While signup (when a user enters the password for the first time) or in case of profile update (if he/she wishes to change password). So I thought maybe we could create a separate function that does this task of hashing before saving it to the database

**Comment by mitalirs** [comment]
@pankajkumarbij, so am I supposed to write the hash password function or not?

**Comment by pankajkumarbij** [comment]
@mitalirs You can write the hash password function and make sure after changing the code signup and signing for students and employers both should work.
