### ISSUE TITLE
Correction on homepage

### ISSUE THREAD

**Issue by sakshi-s** [pankajkumarbij/easy-job-intern#151]
Presently, in the lists for Internship By Industry, Internship By Location, Internship By Stream and Online Trainings by Us, the first row has an oddly larger size than rest like: 
![before2](https://user-images.githubusercontent.com/39264146/112732445-0517a480-8f60-11eb-8361-0a717e43a913.PNG)

I will make them even as follows:
![after2](https://user-images.githubusercontent.com/39264146/112732479-31cbbc00-8f60-11eb-9089-8fd32791d17f.PNG)

## Environment:
 - OS: Windows
 - Browser: Chrome

**Comment by pankajkumarbij** [comment]
@sakshi-s Go ahead and suggest if you are able to make the best home page UI.

You can create another issue related to the improvement of the home page UI if you can.

**Comment by pankajkumarbij** [comment]
@sakshi-s any update?

**Comment by sakshi-s** [comment]
I'll make the PR for my issue by tomorrow evening. I have my exams going on. For the issue of the new homepage, maybe you can open a new issue and someone else could take it up.

**Comment by pankajkumarbij** [comment]
@sakshi-s ok prepare for the exam first and after that work on it.

**Comment by pankajkumarbij** [comment]
@sakshi-s Any update and we do not need this home page actually we need a different and better home page so I don't want to work on this issue but If you want to do work then you can make a PR.
