### ISSUE TITLE
Get started should disappear after login/signin

### ISSUE THREAD

**Issue by EkjotKaur** [pankajkumarbij/easy-job-intern#156]
Get started option takes to sign in option even if we are logged in.
This option is not needed after we have logged in.

Please assign me this issue @pankajkumarbij @asi309 @palashgdev @Vidit-jindal

**Comment by asi309** [comment]
What are the changes u suggest?
Please walk us through how u will solve this issue @EkjotKaur

**Comment by asi309** [comment]
@pankajkumarbij pls assign this issue to @EkjotKaur

**Comment by pankajkumarbij** [comment]
@EkjotKaur At this time get started button is linked with the signup page because login-related work is remaining.

After login a student or an employer there should be show email and logout button etc.

That issue is already assigned to others.

If that work is done I will assign it to you.

**Comment by EkjotKaur** [comment]
@pankajkumarbij  any update? When can I start working on it.

**Comment by palashgupta98** [comment]
Please proceed if you want to take the issue

**Comment by EkjotKaur** [comment]
@palashgdev @pankajkumarbij please assign me this issue.

**Comment by palashgupta98** [comment]
@pankajkumarbij please assign the issue to @EkjotKaur .. i am not able to achieve the same i think due to the permission

**Comment by pankajkumarbij** [comment]
@EkjotKaur Now I have assigned you, start working on it.

**Comment by EkjotKaur** [comment]
> @EkjotKaur Now I have assigned you, start working on it.

Okay
