### ISSUE TITLE
Clearer instruction for local setup and running

### ISSUE THREAD

**Issue by Subham142** [pankajkumarbij/easy-job-intern#159]
make changes in the readme  so that contributors can work and run the frontend and backend separately

## Screenshots for reference
![Screenshot (43)](https://user-images.githubusercontent.com/60570595/113028611-17385380-91a9-11eb-94c6-9bf00d142c29.png)

**Comment by Subham142** [comment]
@pankajkumarbij  please assign it to me and add the labels

**Comment by pankajkumarbij** [comment]
@Subham142 Go ahead and add clear guidelines in contributing.MD file. (Don't change in Readme.MD file)
