### ISSUE TITLE
Employee Login, getting logged as student

### ISSUE THREAD

**Issue by EkjotKaur** [pankajkumarbij/easy-job-intern#163]
- [x] There is an error in server side employee auth file
- [x] When I Register as student and login as employee, it successfully login without any error.  The post request is being send to student login.

Please assign me this issue @pankajkumarbij @asi309 @palashgdev @Vidit-jindal.

**Comment by pankajkumarbij** [comment]
@EkjotKaur Go ahead.

**Comment by pankajkumarbij** [comment]
@EkjotKaur After merging your PR validation format is changed, I think you are installed jquery in react.
Please fix it in this PR.

![Screenshot from 2021-04-06 20-29-07](https://user-images.githubusercontent.com/59636849/113732305-1bb7bb80-9717-11eb-9bcb-83760688df1a.png)
![Screenshot from 2021-04-06 20-29-12](https://user-images.githubusercontent.com/59636849/113732327-1fe3d900-9717-11eb-81a5-75372ed98f93.png)
![Screenshot from 2021-04-06 20-29-15](https://user-images.githubusercontent.com/59636849/113732331-21150600-9717-11eb-84aa-c06f1a8599c0.png)

**Comment by EkjotKaur** [comment]
> @EkjotKaur After merging your PR validation format is changed, I think you are installed jquery in react.
> Please fix it in this PR.
> 
> ![Screenshot from 2021-04-06 20-29-07](https://user-images.githubusercontent.com/59636849/113732305-1bb7bb80-9717-11eb-9bcb-83760688df1a.png)
> ![Screenshot from 2021-04-06 20-29-12](https://user-images.githubusercontent.com/59636849/113732327-1fe3d900-9717-11eb-81a5-75372ed98f93.png)
> ![Screenshot from 2021-04-06 20-29-15](https://user-images.githubusercontent.com/59636849/113732331-21150600-9717-11eb-84aa-c06f1a8599c0.png)

Okay
