### ISSUE TITLE
Remove Warnings

### ISSUE THREAD

**Issue by Subham142** [pankajkumarbij/easy-job-intern#167]
## Describe the bug
 Lots of warnings are showing in the  console

![Screenshot (66)](https://user-images.githubusercontent.com/60570595/113755329-d2bf3180-972d-11eb-93b8-c74490823275.png)

**Comment by Subham142** [comment]
@pankajkumarbij  please assign it to me and add the labels

**Comment by pankajkumarbij** [comment]
@Subham142 Go ahead.
Make sure after changes all the code each and everything should be work properly.
