### ISSUE TITLE
Unauthenticated user should not be able access create Internship page and Authenticated user should not be able to login signup pages

### ISSUE THREAD

**Issue by EkjotKaur** [pankajkumarbij/easy-job-intern#170]
- [x] If the user is logged in then should not be able to access login signup page
- [x] If the user is not logged in then should not be able to access create internship page
- [x] Student should not be able to access create internship page this right should only be available to the employee.
- [x] As student and employee should have different rights then they should user type in user context.

@pankajkumarbij @asi309 @palashgdev @Vidit-jindal please assign me this issue.

**Comment by pankajkumarbij** [comment]
@EkjotKaur Go ahead.
