### ISSUE TITLE
Backend for posting new job form

### ISSUE THREAD

**Issue by EkjotKaur** [pankajkumarbij/easy-job-intern#173]
- [x] creating schema for job
- [x]  creating post api for job form
- [x]  connecting it to the client side.

@pankajkumarbij @asi309 @palashgdev @Vidit-jindal please assign me this issue.

**Comment by himanshujaidka** [comment]
@EkjotKaur are you working on this?

**Comment by EkjotKaur** [comment]
> @EkjotKaur are you working on this?

Yes
