### ISSUE TITLE
Displaying Internships Page

### ISSUE THREAD

**Issue by EkjotKaur** [pankajkumarbij/easy-job-intern#178]
- [x] Displaying all the internships on a single page.
- [x] Connecting it to backend

@pankajkumarbij @asi309 @palashgdev @Vidit-jindal please assign me this issue.

**Comment by pankajkumarbij** [comment]
@EkjotKaur Go ahead

**Comment by pankajkumarbij** [comment]
@EkjotKaur Add one more field in Create Job page ``` Start Job Month ```
And in create internship page add two more fields ``` Start Internship Month``` and ```End Internship Month```

With this PR add this work also and connect with backend both new fields.

Thanks.

**Comment by EkjotKaur** [comment]
> @EkjotKaur Add one more field in Create Job page `Start Job Month`
> And in create internship page add two more fields ` Start Internship Month` and `End Internship Month`
> 
> With this PR add this work also and connect with backend both new fields.
> 
> Thanks.

Okay, I'll.
