### ISSUE TITLE
Design Contact us page.

### ISSUE THREAD

**Issue by pankajkumarbij** [pankajkumarbij/easy-job-intern#18]
Design contact us page using react and react-bootstrap.

**Comment by Devenkapoor7303** [comment]
can i work on this issue

**Comment by pankajkumarbij** [comment]
@Devenkapoor7303  go ahead

**Comment by arbazalam01** [comment]
is this issue still open

**Comment by Devenkapoor7303** [comment]
I was working on it sorry for being late

**Comment by Devenkapoor7303** [comment]
Is this looking okay?

![Capture](https://user-images.githubusercontent.com/73438023/108588215-d5e09880-730c-11eb-9699-fa7702009433.PNG)

**Comment by pankajkumarbij** [comment]
> Is this looking okay?
> 
> ![Capture](https://user-images.githubusercontent.com/73438023/108588215-d5e09880-730c-11eb-9699-fa7702009433.PNG)

Use the form border and make sure it should be responsive then make a PR.

**Comment by Devenkapoor7303** [comment]
Okay
