### ISSUE TITLE
Modifying animation

### ISSUE THREAD

**Issue by Castella1313** [pankajkumarbij/easy-job-intern#181]
Modifying animation 

https://user-images.githubusercontent.com/53293156/114052613-cf51b480-98ab-11eb-9237-63708f08a319.mov

rather than scaling up the whole block, we can scale up the single entries inside it.

for example if the user hovers on Marketing, only that block should be scaled up!

**Comment by Castella1313** [comment]
@pankajkumarbij May I work on this? This will help in improving the user interface :)

**Comment by pankajkumarbij** [comment]
@Castella1313 Go ahead.
