### ISSUE TITLE
Connecting all Job frontend to backend and dynamic values from DB in react 

### ISSUE THREAD

**Issue by EkjotKaur** [pankajkumarbij/easy-job-intern#188]
- [x]  Connecting all internships page with the backend
- [x]  Adding values from database in place of static values

@pankajkumarbij @asi309 @palashgdev @Vidit-jindal assign me this issue.

**Comment by pankajkumarbij** [comment]
@EkjotKaur Go ahead

**Comment by pankajkumarbij** [comment]
@EkjotKaur And at the end of every card there should be a button of Apply Now.

And you can open some issues for freshers jobs also same like internships pages create freshers job, connect with backend and show all the jobs for freshers on a page.

And add one more field for jobs page ```Year of Experience``` need for the job.

There are no experience fields for freshers job.

Add jobs and internship page links in the navbar.

You can open any no of issues that you want and start working on it I will assign you.
