### ISSUE TITLE
Filters while looking for jobs and internships (backend)

### ISSUE THREAD

**Issue by mitalirs** [pankajkumarbij/easy-job-intern#201]
## Using filters while looking for jobs and internships
A student is currently not allowed to search for jobs/internships with filters

The backend logic I'll add will enable a student to look for jobs/internships using filters:
1. location
2. duration
3. tech stack
4. company name
5. start date

@pankajkumarbij I will work on the backend part of this, could you please assign this issue to me?

**Comment by pankajkumarbij** [comment]
@mitalirs Go ahead
