### ISSUE TITLE
Edit Internship Form for the post internship by the employee

### ISSUE THREAD

**Issue by EkjotKaur** [pankajkumarbij/easy-job-intern#206]
- [x] Posted internship could also to edited by the employee 
- [x] A dialogue box would open and could only edit and add some fields

@pankajkumarbij @asi309 @palashgdev @Vidit-jindal assign me this issue.

**Comment by pankajkumarbij** [comment]
@EkjotKaur Please pull all the changes from the repo because I have updated something.

**Comment by EkjotKaur** [comment]
> @EkjotKaur Please pull all the changes from the repo because I have updated something.

Okay
