### ISSUE TITLE
Edit Job Backend and connect to frontend

### ISSUE THREAD

**Issue by EkjotKaur** [pankajkumarbij/easy-job-intern#216]
- [x]  Creating API for editing job
- [x]  Connecting it to the job form

@pankajkumarbij @asi309 @palashgdev @Vidit-jindal assign me this issue.

**Comment by pankajkumarbij** [comment]
@EkjotKaur Some errors are there after merging some PR please check and let me know.

![Screenshot from 2021-04-12 19-41-00](https://user-images.githubusercontent.com/59636849/114413342-87909d00-9bcb-11eb-8788-0fec6a2d192e.png)

![Screenshot from 2021-04-12 19-40-24](https://user-images.githubusercontent.com/59636849/114413338-865f7000-9bcb-11eb-80dc-93b3521ff6d6.png)

![Screenshot from 2021-04-12 19-40-15](https://user-images.githubusercontent.com/59636849/114413324-83647f80-9bcb-11eb-982f-56b414d7049b.png)

Check it and try to fix small errors in the project.

**Comment by EkjotKaur** [comment]
Okay, I'll try to fix.
