### ISSUE TITLE
some images needs margin in mobile view(frontend)

### ISSUE THREAD

**Issue by gnikita432** [pankajkumarbij/easy-job-intern#221]
## Describe the bug
In mobile view the some images needs margin and should be aligned at center so that the columns will look seprate
![easyjobintern](https://user-images.githubusercontent.com/61223163/114419389-00debe80-9bd1-11eb-92bb-63291f4260c3.PNG)

## To Reproduce
1. 
2. 
3. 
4. 

## Logs
If applicable, add logs to help explain your problem (e.g. the error message and/or exception traceback).

## Environment (please complete the following information):
 - OS:windows
 - Browser:chrome

**Comment by pankajkumarbij** [comment]
@gnikita432 We don't need this home page actually this home page is temporary we will improve the home page differently after all other functionality will complete.

**Comment by pankajkumarbij** [comment]
Thanks for opening an issue.
