### ISSUE TITLE
hover effect on icons(frontend)

### ISSUE THREAD

**Issue by gnikita432** [pankajkumarbij/easy-job-intern#222]
## Is your feature request related to a problem? Please describe.
the icons below contact with us should have some hover effect
![easyjobintern1](https://user-images.githubusercontent.com/61223163/114420444-f40e9a80-9bd1-11eb-8b1c-7250e99c0a20.PNG)

## Additional context
Add any other context about the feature request here.

**Comment by pankajkumarbij** [comment]
@gnikita432 Go ahead.
