### ISSUE TITLE
search for a particular internship (employer backend)

### ISSUE THREAD

**Issue by mitalirs** [pankajkumarbij/easy-job-intern#227]
This will help a recruiter to search for a particular internship (only the ones posted by him/her).
They will be able to search by the following parameters:
1. duration
2. tech stack
3. stipend
4. start date

Adding this will help the recruiter to keep a track of his/her posts.
This route will need the employer to be authenticated, so auth_employer middleware will be used.

**Comment by pankajkumarbij** [comment]
@mitalirs Go ahead
