### ISSUE TITLE
Required field length should be greater than 8

### ISSUE THREAD

**Issue by himanshujaidka** [pankajkumarbij/easy-job-intern#229]
![Screenshot (207)](https://user-images.githubusercontent.com/58654018/114560997-cd606a80-9c8a-11eb-8542-88941b487a16.png)
It is mentioned that the required password length should be greater than 8 but, when password=8, the warning get closed, so it should be password>8 or we should change the warning as "Required field length should be greater than 7"
![Screenshot (208)](https://user-images.githubusercontent.com/58654018/114561437-30ea9800-9c8b-11eb-983f-0905d00f9904.png)
@pankajkumarbij pls assign this to me

**Comment by pankajkumarbij** [comment]
@himanshujaidka Go ahead.
