### ISSUE TITLE
Adding a Loading Spinner till fetching of data for internships/jobs/fresher job is not complete

### ISSUE THREAD

**Issue by kartikpuri99** [pankajkumarbij/easy-job-intern#237]
## Is your feature request related to a problem? Please describe.
Right now there is no loading spinner when a person click on all internship/jobs/freshers job.When we are fetching data from the database there is blank screen.

## Describe the solution you'd like
I want to add the loading spinner in all the three cases .Please assign this issue to me.

**Comment by pankajkumarbij** [comment]
@kartikpuri99 Go ahead and make sure After changes your code before making a PR please check that all functionality should work.
