### ISSUE TITLE
Adding vacancy/job openings + position/role

### ISSUE THREAD

**Issue by mitalirs** [pankajkumarbij/easy-job-intern#243]
### Adding the number of vacancies/openings 
Currently, there is no' available openings' field on the internship/job/fresher job model
I will add the 'vacancy' field to these 3 models
This will give the applicant an idea about available openings for a job

### Adding the position/role 
Currently, there is no 'position'/'role' field on the internship/job/fresher job model
I will add the 'role' field to these 3 models
This will give the applicant a clear idea about the role/position he/she is applying for

@pankajkumarbij, can you please assign this issue to me?

**Comment by pankajkumarbij** [comment]
@mitalirs Add field in frontend and backend both.

**Comment by mitalirs** [comment]
@pankajkumarbij, for the frontend, I have to make changes only to that part of the code when an employer creates a new job/internship, right?
ie src/Components/CreateNew (all 3 files in this folder)

**Comment by pankajkumarbij** [comment]
@mitalirs yes you have to add fields in these forms at the time of crate a new job/internship etc. and change the backend part accordingly.
