### ISSUE TITLE
Write unit tests for backend.

### ISSUE THREAD

**Issue by Sushi22** [pankajkumarbij/easy-job-intern#246]
## Is your feature request related to a problem? Please describe.
No

## Describe the solution you'd like
Adding unit tests for each component in the backend .

## Additional context
Documenting the API endpoints using swagger.

**Comment by Sushi22** [comment]
Hello I am participant under GSSoC'21.
@pankajkumarbij  can you please assign this issue to me ?
I would like to  work on this :)

**Comment by pankajkumarbij** [comment]
@Sushi22 Thanks for opening an issue but at this time we do not need this. first we want to complete all the features that need for this project.
