### ISSUE TITLE
Backend for get Internship by location 

### ISSUE THREAD

**Issue by EkjotKaur** [pankajkumarbij/easy-job-intern#250]
API for Getting Internships based to location for the "Get Internships By Location Page"

@pankajkumarbij @asi309 @palashgdev @Vidit-jindal assign me this issue.

**Comment by pankajkumarbij** [comment]
look at some filter-related backend code what he has done is useful for you or not and how we can filter internships and all.

Some search and filter-related PR is already merged.

Are you make a frontend for that page also or the only the backend?

**Comment by EkjotKaur** [comment]
Backend and frontend both.

**Comment by pankajkumarbij** [comment]
@EkjotKaur ok Go ahead and open issue for front end also whenever you want to work.

**Comment by EkjotKaur** [comment]
The code right now shows those Internships jobs that are selected by the the user as per stipend states locations and all.

I want to make it for all the internships and jobs under one location

**Comment by pankajkumarbij** [comment]
@EkjotKaur ok, you can write another backend things for that.
