### ISSUE TITLE
bookmark internship (backend)

### ISSUE THREAD

**Issue by mitalirs** [pankajkumarbij/easy-job-intern#259]
## Bookmark internship
- This route can be used to bookmark an internship for later review (can be thought of as something similar to 'watch later' on a streaming app). 
- While searching for internships a student shortlists a few of them and applies to one or more from the shortlisted ones, bookmarking them will save his/her efforts as he/she can view all the bookmarked internships. in one go 
- This will also help the student to compare between them as all the roles he/she shortlisted will be in one place

## Solution
1. Create a bookmarkedBy field in the Internship model. It will be an array of ObjectIds of the students who have bookmarked that particular internship
2. To bookmark an internship, a student will go to a POST route (that will take id of a particular internship as a parameter) and send an object with a 'bookmark' attribute either set to true or false. If the attribute is set to true then the student's id will be appended to the bookmarkedBy array of that particular internship. If it is set to false the id of the student will be removed from the list.

This POST route will require the student to be authenticated
I wish to work on the backend logic of this

@pankajkumarbij, can you please assign this issue to me

**Comment by pankajkumarbij** [comment]
@mitalirs are you done frontend also for this part?

**Comment by mitalirs** [comment]
@pankajkumarbij, actually I wish to work on the backend logic only particularly

**Comment by pankajkumarbij** [comment]
@mitalirs Go ahead and give clear description on PR how to use it on frontend.

**Comment by mitalirs** [comment]
> @mitalirs Go ahead and give clear description on PR how to use it on frontend.

Sure, thank you for assigning!
