### ISSUE TITLE
github action to add autolabel of gssoc on PR and issues

### ISSUE THREAD

**Issue by Ankita297** [pankajkumarbij/easy-job-intern#262]
## Is your feature request related to a problem? Please describe.
github action to add autolabel of gssoc on PR and issues

## Describe the solution you'd like
I want to add github action for that .
## Additional context
Add any other context about the feature request here.

**Comment by Ankita297** [comment]
@pankajkumarbij can i work on this ?

**Comment by pankajkumarbij** [comment]
@Ankita297 Go ahead.
