### ISSUE TITLE
auto close issue if corresponding PR got merged .

### ISSUE THREAD

**Issue by Ankita297** [pankajkumarbij/easy-job-intern#265]
## Is your feature request related to a problem? Please describe.
github action to auto close issue if corresponding PR got merged .
## Additional context
Add any other context about the feature request here.

**Comment by Ankita297** [comment]
@pankajkumarbij  can i work on this ?

**Comment by pankajkumarbij** [comment]
@Ankita297 this feature is working already when an issue is linked with that PR.

**Comment by Ankita297** [comment]
@pankajkumarbij  as you can see if contributor makes PR .

Then PR template does not appear .

![Home_external tutor by akshay1027 · Pull Request #122 · Namanl2001_MERN-Gurujii-dev - Google Chrome 23-04-2021 18_32_53](https://user-images.githubusercontent.com/67833077/115875165-8e889c80-a462-11eb-900e-0b1684322219.png)

![Home_external tutor by akshay1027 · Pull Request #122 · Namanl2001_MERN-Gurujii-dev - Google Chrome 23-04-2021 18_32_36](https://user-images.githubusercontent.com/67833077/115875153-8cbed900-a462-11eb-8600-f4d6ef7da1ef.png)

**Comment by Ankita297** [comment]
So if you contributor uses wrong keyword the issue will not be closed .
