### ISSUE TITLE
 Entire UI/UX design

### ISSUE THREAD

**Issue by codebuzzer01** [pankajkumarbij/easy-job-intern#275]
## Is your feature request related to a problem? Please describe.
I would like to enhance the UI/UX features of whole website (for ex- Navbar is not sticky, footer should not be opaque etc)

## Describe the solution you'd like
Implement UI/UX skills to change the entire look of website.

**Comment by codebuzzer01** [comment]
@pankajkumarbij should I work on it?

**Comment by pankajkumarbij** [comment]
@codebuzzer01 Go ahead and check every page of the web site, some pages like job/internship pages are looking after login only and first need to create internships and jobs after login as a employer so you can see all the functionality.

**Comment by codebuzzer01** [comment]
Hey @pankajkumarbij  will you please elaborate what you said above?

**Comment by pankajkumarbij** [comment]
Some pages like view all jobs/internship etc pages are only showing after login.

After login as a employer and create some jobs/internship so you can able to see the list of jobs/internships.

You can explore the website more.

**Comment by pankajkumarbij** [comment]
@codebuzzer01 are you working on this issue?
