### ISSUE TITLE
UI of 404 page 

### ISSUE THREAD

**Issue by Ankita297** [pankajkumarbij/easy-job-intern#280]
## Is your feature request related to a problem? Please describe.
Current ui is very simple I  want to enhance it .
## Additional context
Add any other context about the feature request here.

**Comment by Ankita297** [comment]
@pankajkumarbij Can i work on this ?

**Comment by pankajkumarbij** [comment]
@Ankita297 One issue is already opend for improve entire UI design of website.

SO this part is cover in that issue. 

If this part is not done with that PR then you can work in future.

**Comment by Ankita297** [comment]
Can i work on this now  @pankajkumarbij ?

**Comment by pankajkumarbij** [comment]
@Ankita297 Go ahead
