### ISSUE TITLE
delete employer profile (backend)

### ISSUE THREAD

**Issue by mitalirs** [pankajkumarbij/easy-job-intern#284]
## delete employer profile (backend)
Currently, there is no route for an employer to delete their profile

## Solution
Creating a delete employer profile route. This will delete that particular employer's entry from the collection. Also, all the internships/jobs/fresherJobs created by that employer will be deleted

**Comment by pankajkumarbij** [comment]
@mitalirs are you working on this issue?

**Comment by mitalirs** [comment]
Yes, Actually I am having my exams, I will create a PR as soon as possible. Thank you.

**Comment by pankajkumarbij** [comment]
> possible

ok Focus on your exam first after that you can continue.
