### ISSUE TITLE
Frontend: Footer

### ISSUE THREAD

**Issue by Vishruta-Patil** [pankajkumarbij/easy-job-intern#287]
## Is your feature request related to a problem? Please describe.
I want to work in footer part. 
## Describe the solution you'd like
I want to change the footer's frontend part. I will create cutomize footer
## Additional context
Add any other context about the feature request here.

**Comment by Vishruta-Patil** [comment]
@Vidit-jindal can you assign this issue as a GSSoC participant

**Comment by pankajkumarbij** [comment]
@Vishruta-Patil I think footer is fine as of now.
What are you going to change?

**Comment by Vishruta-Patil** [comment]
@pankajkumarbij I can add newsletter subscription button where users can subscribe so that will not leave any updates

**Comment by pankajkumarbij** [comment]
@Vishruta-Patil Go ahead and make sure footer should remain responsive.

**Comment by pankajkumarbij** [comment]
@Vishruta-Patil are you going to add only a input box and button in front end part.
Right?
