### ISSUE TITLE
design a new logo for the project

### ISSUE THREAD

**Issue by pankajkumarbij** [pankajkumarbij/easy-job-intern#3]
Design a new standard logo for the website.

**Comment by Nirbhay1910** [comment]
Hi, pls assign this issue to me

**Comment by pankajkumarbij** [comment]
> Hi, pls assign this issue to me

Go ahead

**Comment by Nirbhay1910** [comment]
> > Hi, pls assign this issue to me
> 
> Go ahead

okay thanks
