### ISSUE TITLE
search bookmarked internship (backend)

### ISSUE THREAD

**Issue by mitalirs** [pankajkumarbij/easy-job-intern#304]
## Is your feature request related to a problem? Please describe.
currently, a user has no facility to search for a bookmarked internship based on various parameters (like id, role, vacancy, etc)

## Describe the solution you'd like
a route that allows user to search for internships from the list of bookmarked Internships 

@pankajkumarbij, could you please assign this issue to me?

**Comment by pankajkumarbij** [comment]
@mitalirs Go ahead
