### ISSUE TITLE
search bookmarked job (backend)

### ISSUE THREAD

**Issue by mitalirs** [pankajkumarbij/easy-job-intern#305]
## Is your feature request related to a problem? Please describe.
currently, a user has no facility to search for a bookmarked job/fresher job based on various parameters (like id, role, vacancy, etc)

## Describe the solution you'd like
a route that allows user to search for jobs/fresher jobs from the list of bookmarked jobs/fresher jobs 

@pankajkumarbij, could you please assign this issue to me?

**Comment by pankajkumarbij** [comment]
@mitalirs make it for job and freshers job both
