### ISSUE TITLE
Improve About Us page

### ISSUE THREAD

**Issue by pankajkumarbij** [pankajkumarbij/easy-job-intern#32]
Improve the About us page.

- You can put dummy any data as of now.
- About us the page should be in dark mode with the best color combination because this website is building up in dark mode.
- Make sure use only react-bootstrap and CSS for style, don't use any other styling framework or libraries. 
- Make sure every page should be responsive on every platform.

**Comment by raman-thakur** [comment]
can you assign this to me?

**Comment by kunal299** [comment]
@pankajkumarbij Can you assign this issue to me as a part of gssoc'21?

**Comment by pankajkumarbij** [comment]
> @pankajkumarbij Can you assign this issue to me as a part of gssoc'21?

@kunal299 I can assign one issue at a time.
The coding period starts from 8th march 2021 (timeline updated)

**Comment by sukhpreet-singh1** [comment]
can you please assign me this issue?

**Comment by pankajkumarbij** [comment]
@sukhpreet-singh1 go-ahead

Are you part of any open source program?

**Comment by sukhpreet-singh1** [comment]
yeah i am participant for GSSOC 
but very excited for open source i would like do from now only

**Comment by pankajkumarbij** [comment]
> yeah i am participant for GSSOC
> but very excited for open source i would like do from now only

yeah, you can contribute at any time to any issue.

**Comment by sukhpreet-singh1** [comment]
@pankajkumarbij  should i use same color schema as used on home page?

**Comment by pankajkumarbij** [comment]
@sukhpreet-singh1 home page design is not yet completed it required improvement, you can use a different color schema but colors should standard match with the dark theme.

**Comment by sukhpreet-singh1** [comment]
ok sure and should i put  issues which i found ?

**Comment by kunal299** [comment]
@pankajkumarbij But I'm working on this issue.

**Comment by kunal299** [comment]
@pankajkumarbij Aren't issues given on the basis of first-come first-serve?

**Comment by pankajkumarbij** [comment]
@kunal299 I am very sorry, I was thinking that you are work only when GSSOC coding period starts.
You also comment on the sign-up sign-in issue you can work on that I am assigning you now.

**Comment by sukhpreet-singh1** [comment]
@pankajkumarbij i found some issue ,should i create them so more people can work on them ?

**Comment by pankajkumarbij** [comment]
> @pankajkumarbij i found some issue ,should i create them so more people can work on them ?

@sukhpreet-singh1 sure you can open issues always if any found.
