### ISSUE TITLE
Frontend and backend to get Job and fresherjob group by industry

### ISSUE THREAD

**Issue by kartikpuri99** [pankajkumarbij/easy-job-intern#321]
## Is your feature request related to a problem? Please describe.
I want to write the frontend and backend code to get a job group by industry. Please assign this issue to me @pankajkumarbij

**Comment by pankajkumarbij** [comment]
@kartikpuri99 this feature is already there in the project.

**Comment by kartikpuri99** [comment]
@pankajkumarbij  It is for internship i donot see it for jobs and fresherjobs

**Comment by pankajkumarbij** [comment]
@kartikpuri99 it is available in the backend you can see it, it's not in the frontend.

**Comment by pankajkumarbij** [comment]
@kartikpuri99 Go ahead and make a similar design as an internship on the home page for job and freshers job that backend is already available for all.

**Comment by kartikpuri99** [comment]
okay i will do it for fresher job and job
