### ISSUE TITLE
Improve Contact US page

### ISSUE THREAD

**Issue by pankajkumarbij** [pankajkumarbij/easy-job-intern#33]
Improve the Contact US page.

- You can use input fields first name, email, mobile no, message and you can suggest other features also.
- Contact US the page should be in dark mode with the best color combination because this website is building up in dark mode.
- Make sure use only react-bootstrap and CSS for style, don't use any other styling framework or libraries. 
- Make sure every page should be responsive on every platform.

**Comment by raman-thakur** [comment]
can you assign this to me?

**Comment by pankajkumarbij** [comment]
> can you assign this to me?

One issue at a time can be assigned.

**Comment by pankajkumarbij** [comment]
@raman-thakur Now You can Work on this issue.

**Comment by pankajkumarbij** [comment]
@raman-thakur are you working on this issue?

**Comment by sukhpreet-singh1** [comment]
assign me for this if no one working on this issue

**Comment by pankajkumarbij** [comment]
> assign me for this if no one working on this issue

Go-ahead

**Comment by akshay1027** [comment]
I would like to work on this @pankajkumarbij
