### ISSUE TITLE
Improve NavBar

### ISSUE THREAD

**Issue by pankajkumarbij** [pankajkumarbij/easy-job-intern#34]
Improve the Navbar

- Remove this logo because this logo's height is not fit the navbar(You can give brand name only if you don't want to design a logo)
- For all dropdown nav items there should be the effect of hover or animation effect.
- Nav items:-
         1. Internships dropdown (dropdown items should be some categories like part-time, engineering, MBA, etc., (you suggest and add other categories).
         2. Freshers Jobs dropdown (dropdown items should be some categories like part-time, full-time, engineering, MBA, etc., (you suggest and add other categories).
         3. All Open Jobs dropdown(dropdown items should be some categories like -time, full-time, engineering, MBA, etc., (you suggest and add other categories).
         4. Blogs Button.
         5. Login Button dropdown(dropdown items should have two options Student and Employer).
         6. Sign UP Button dropdown(dropdown items should have two options Student and Employer).
  
- NavBar the page should be in dark mode with the best color combination because this website is building up in dark mode.
- Make sure use only react-bootstrap and CSS for style, don't use any other styling framework or libraries.
- Make sure every page should be responsive on every platform.

**Comment by Piyushjakhar** [comment]
Hey! Can i use Popper.js for dropdowns?

**Comment by pankajkumarbij** [comment]
@Piyushjakhar yeah, you can use it.
Would you like to work on this issue?

**Comment by Piyushjakhar** [comment]
yes already on it:)

**Comment by Piyushjakhar** [comment]
@pankajkumarbij please assign it to me

**Comment by pankajkumarbij** [comment]
@Piyushjakhar are you part of any open source program?

**Comment by Piyushjakhar** [comment]
@pankajkumarbij yes GSSOC'21

**Comment by pankajkumarbij** [comment]
> @pankajkumarbij yes GSSOC'21

GSSOC'21 timeline has been updated coding period starts from 8 March.

**Comment by Piyushjakhar** [comment]
will I be getting any points if I solve this issue before 8th March?

**Comment by pankajkumarbij** [comment]
> will I be getting any points if I solve this issue before 8th March?

@Piyushjakhar you will be getting points after the coding period start.

**Comment by sukhpreet-singh1** [comment]
if you allow i will like to work on this issue

**Comment by pankajkumarbij** [comment]
@Piyushjakhar any update ?

**Comment by pankajkumarbij** [comment]
> if you allow i will like to work on this issue

@sukhpreet-singh1 wait till tomorrow for the reply that he working on this issue or not.

**Comment by sukhpreet-singh1** [comment]
ok
k

**Comment by Piyushjakhar** [comment]
yes i am working on that issue
i was just waiting for the coding period to start

**Comment by Piyushjakhar** [comment]
Hey I have made a seperate branch and tried to push to that branch, but it says you dont have access to do so

**Comment by Piyushjakhar** [comment]
And regarding the issue of navbar, i have almost updated it with all the requirements but struggling in the css part of search bar to make it responsive.
please help me out in this.

**Comment by pankajkumarbij** [comment]
> Hey I have made a seperate branch and tried to push to that branch, but it says you dont have access to do so

@Piyushjakhar send me some screenshots.

**Comment by Piyushjakhar** [comment]
![Capture](https://user-images.githubusercontent.com/29627742/110342216-28ca8780-8051-11eb-9438-2ca9610abe12.PNG)

**Comment by Piyushjakhar** [comment]
here i have made a seperate branch named as navbar and then tried to push into that

**Comment by pankajkumarbij** [comment]
@Piyushjakhar first you have to push the branch in your forked repo after that there will be an option for Compare and pull request.
read contributing.md file.

**Comment by Piyushjakhar** [comment]
Hey i have made a pull request.
please help me in the issue mentioned in the pull request description.
Thanks
