### ISSUE TITLE
Frontend for Get Jobs By industry

### ISSUE THREAD

**Issue by EkjotKaur** [pankajkumarbij/easy-job-intern#346]
- [x]  Creating new page for Job by industry under the drop down
- [x]  Designing it
- [x]  The page will contain Jobs grouped by their industry
- [x]  Connecting to backend
- [x]  Connecting to navbar

@pankajkumarbij @asi309 @palashgdev @Vidit-jindal assign me this issue.

**Comment by pankajkumarbij** [comment]
@EkjotKaur is this issue is completed or pending?

**Comment by EkjotKaur** [comment]
completed

**Comment by pankajkumarbij** [comment]
@EkjotKaur there is no PR related to it so I have to close it?
or job by the company is not working you can update this issue and resolve them.

**Comment by pankajkumarbij** [comment]
@EkjotKaur I think you have already solved it with some PR.
