### ISSUE TITLE
Make Home page responsive

### ISSUE THREAD

**Issue by Bhavya-Sehgal** [pankajkumarbij/easy-job-intern#348]
I want to make home page responsive .

{GSSOC'21]

Please assign me this issue @pankajkumarbij @asi309 @palashgdev @Vidit-jindal .

**Comment by Bhavya-Sehgal** [comment]
Sceenshot:

![eji-home](https://user-images.githubusercontent.com/66208607/119495400-0149a800-bd80-11eb-810b-308dfa801f1a.png)

**Comment by pankajkumarbij** [comment]
@Bhavya-Sehgal Go ahead
