### ISSUE TITLE
Improve Login Page and Sign Up page design for Students

### ISSUE THREAD

**Issue by pankajkumarbij** [pankajkumarbij/easy-job-intern#35]
Improve Login Page and Sign Up page design for students

- You can use input fields name, email, mobile no, password, confirm the password, agree on the checkbox, and can suggest other features also for the sign-up page.
- Login page only has email and password input fields and agrees on the checkbox.
- All pages should be in dark mode with the best color combination because this website is building up in dark mode.
- Make sure use only react-bootstrap and CSS for style, don't use any other styling framework or libraries.
- Make sure every page should be responsive on every platform.

**Comment by raman-thakur** [comment]
i would like to work on this

**Comment by pankajkumarbij** [comment]
> i would like to work on this

@raman-thakur read details carefully and Go ahead.

**Comment by raman-thakur** [comment]
form design is good already but the hole page of login and signup is looking messy because of too much colors and not having distance with footer i will work on that @pankajkumarbij

**Comment by pankajkumarbij** [comment]
> form design is good already but the hole page of login and signup is looking messy because of too much colors and not having distance with footer i will work on that @pankajkumarbij

@raman-thakur yeah use the best dark mode type color combination and set the best margin and padding and make sure it should be responsive.
