### ISSUE TITLE
Design Login Page and Sign Up page design for employers or companies.

### ISSUE THREAD

**Issue by pankajkumarbij** [pankajkumarbij/easy-job-intern#36]
Design Login Page and Sign Up page design for employers or companies.

- You can use input fields company name, contact person name, email, mobile no, password, confirm the password, agree on the checkbox, and can suggest other features also for the sign-up page.
- Login page only has email and password input fields and agrees on the checkbox.
- All pages should be in dark mode with the best color combination because this website is building up in dark mode.
- Make sure use only react-bootstrap and CSS for style, don't use any other styling framework or libraries.
- Make sure every page should be responsive on every platform.

**Comment by kunal299** [comment]
@pankajkumarbij I would love to contribute to this issue. Can you assign this issue to me as a part of gssoc'21?

**Comment by pankajkumarbij** [comment]
> @pankajkumarbij I would love to contribute to this issue. Can you assign this issue to me as a part of gssoc'21?

Go ahead.

**Comment by pankajkumarbij** [comment]
> > @pankajkumarbij I would love to contribute to this issue. Can you assign this issue to me as a part of gssoc'21?
> 
> Go ahead.

@kunal299 Timeline has been updated, the coding period starts from 8/3/2021

**Comment by sukhpreet-singh1** [comment]
can you please assign me this issue, i would like to work on it.

**Comment by pankajkumarbij** [comment]
> can you please assign me this issue, i would like to work on it.

@kunal299 are you working on this issue?

**Comment by kunal299** [comment]
@pankajkumarbij yes

**Comment by sukhpreet-singh1** [comment]
@pankajkumarbij can i create a issue regarding improvement of home page?

**Comment by pankajkumarbij** [comment]
> @pankajkumarbij can i create a issue regarding improvement of home page?

@sukhpreet-singh1 yes you can.

**Comment by pankajkumarbij** [comment]
@kunal299 are you working on it? because I have assigned you before 10 days, please give updates about it?

**Comment by pankajkumarbij** [comment]
@kunal299 I have updated the project structure first you pull the changes in your repository and then complete the work and make PR.

**Comment by kunal299** [comment]
> @kunal299 are you working on it? because I have assigned you before 10 days, please give updates about it?

The coding phase started from 8th March so I working from that day.

**Comment by pankajkumarbij** [comment]
@kunal299 ok

**Comment by pankajkumarbij** [comment]
@kunal299 are you working on it or not?

**Comment by kunal299** [comment]
@pankajkumarbij yes

**Comment by kunal299** [comment]
I Will show the work tomorrow. It will be completed by tom.

**Comment by pankajkumarbij** [comment]
> I Will show the work tomorrow. It will be completed by tom.

@kunal299 ok

**Comment by pankajkumarbij** [comment]
@kunal299 Now I can no longer be assigned to you this issue, I will assign it to other students because they want to work on this issue.

You have to make a signup and login form the frontend only.

**Comment by abhinav5481** [comment]
Hi @pankajkumarbij 
I would like to work on this issue. Please assign it to me under crossWoc

**Comment by pankajkumarbij** [comment]
@abhinav5481 Go ahead

@kunal299 Please don't make PR now.

**Comment by kunal299** [comment]
@pankajkumarbij Sorry, as I have commented first on various other projects, I was not able to complete this project. Once again really sorry.

**Comment by pankajkumarbij** [comment]
> @pankajkumarbij Sorry, as I have commented first on various other projects, I was not able to complete this project. Once again really sorry.

@kunal299 It's ok
