### ISSUE TITLE
Backend for get Job by employee name

### ISSUE THREAD

**Issue by Bhavya-Sehgal** [pankajkumarbij/easy-job-intern#362]
API for Getting jobs based to company name for the "Get jobs By Employee name"

@pankajkumarbij @asi309 @palashgdev @Vidit-jindal assign me this issue.

**Comment by pankajkumarbij** [comment]
@Bhavya-Sehgal thanks for opening this issue.
This feature is not that much important please try another issue related to student and employer dashboards.
