### ISSUE TITLE
Backend for get fresher jobs by employee name

### ISSUE THREAD

**Issue by Bhavya-Sehgal** [pankajkumarbij/easy-job-intern#364]
API for Getting freshers jobs based to company name for the "Get freshers jobs By Employee name"

@pankajkumarbij @asi309 @palashgdev @Vidit-jindal assign me this issue.

**Comment by pankajkumarbij** [comment]
@Bhavya-Sehgal Some backend is done related to student and employer dashboard like update delete profile etc. you can work on that frontend if you want.

Thanks.
