### ISSUE TITLE
Integrate contact us page details with the database

### ISSUE THREAD

**Issue by pankajkumarbij** [pankajkumarbij/easy-job-intern#37]
Integrate contact us page details with the database using node.js, express js, and MongoDB.

MongoDB database details should be in our local system means don't use any online platform to store data.

**Comment by sukhpreet-singh1** [comment]
can we store data in MongoDB site ? if yes then assign me i will complete it

**Comment by pankajkumarbij** [comment]
@sukhpreet-singh1 we store data in MongoDB that is installed in our local system.

**Comment by abhinav5481** [comment]
I would like to work on this issue. If it is still open please assign it to me.

**Comment by maanpatel2492** [comment]
> ngoDB database details should be in our local system means don't use any online platform to store data

I can solve this issue.Assign me if possible.
(under GSSOC 21)

**Comment by pankajkumarbij** [comment]
> I would like to work on this issue. If it is still open please assign it to me.

GO ahead

**Comment by pankajkumarbij** [comment]
> > ngoDB database details should be in our local system means don't use any online platform to store data
> 
> I can solve this issue.Assign me if possible.
> (under GSSOC 21)
@maanpatel2492 GSSOC coding period will start from 8th march.

**Comment by maanpatel2492** [comment]
> > > ngoDB database details should be in our local system means don't use any online platform to store data
> > 
> > 
> > I can solve this issue.Assign me if possible.
> > (under GSSOC 21)
> > @maanpatel2492 GSSOC coding period will start from 8th march.

But on their website it is 1st March.

**Comment by pankajkumarbij** [comment]
> > > > ngoDB database details should be in our local system means don't use any online platform to store data
> > > 
> > > 
> > > I can solve this issue.Assign me if possible.
> > > (under GSSOC 21)
> > > @maanpatel2492 GSSOC coding period will start from 8th march.
> 
> But on their website it is 1st March.

The timeline has been updated, check below details

https://docs.google.com/document/d/1pqhhsE1E1-bqn_etHTKhK0fWKR9v1hL_lBAsjTvTbN0/edit

**Comment by maanpatel2492** [comment]
> > > > > ngoDB database details should be in our local system means don't use any online platform to store data
> > > > 
> > > > 
> > > > I can solve this issue.Assign me if possible.
> > > > (under GSSOC 21)
> > > > @maanpatel2492 GSSOC coding period will start from 8th march.
> > 
> > 
> > But on their website it is 1st March.
> 
> The timeline has been updated, check below details
> 
> https://docs.google.com/document/d/1pqhhsE1E1-bqn_etHTKhK0fWKR9v1hL_lBAsjTvTbN0/edit

okay,thanks

**Comment by Faizanrz7** [comment]
@pankajkumarbij  I would like to work in this issue as a part of gssoc'21, assign me if possible

**Comment by pankajkumarbij** [comment]
@abhinav5481 are you working on it?

**Comment by abhinav5481** [comment]
Yeah I'm working on it. Please give me some more time. I will try to create a PR by today EOD.

**Comment by pankajkumarbij** [comment]
> Yeah I'm working on it. Please give me some more time. I will try to create a PR by today EOD.

@abhinav5481 keep it up

**Comment by abhinav5481** [comment]
> Yeah I'm working on it. Please give me some more time. I will try to create a PR by today EOD.

Hi @pankajkumarbij 
I had contributed to this issue 16 days ago. I'm a participant GSSOC'21. Will this PR would be counted for GSSOC'21?

**Comment by pankajkumarbij** [comment]
@abhinav5481 If your PR merged after 8 march 2021 then it will counted in GSSOC'21.
