### ISSUE TITLE
Typo in README.md

### ISSUE THREAD

**Issue by iamansoni** [pankajkumarbij/easy-job-intern#40]
There is a spelling mistake for the word `fork` under the `Contribution Guidelines` in the readme.md file.

![e0](https://user-images.githubusercontent.com/26296983/109425682-7458b200-7a0f-11eb-8e4b-8c9611082b1a.JPG)

**Comment by pankajkumarbij** [comment]
@iamansoni Go ahead and correct if any other typo mistakes in the readme.

**Comment by vrouilhac** [comment]
I saw the suggestions and I propose you a new version for your Readme.md. Please let me know if you like it.
#41
