### ISSUE TITLE
Frontend for Creating form for Online Training

### ISSUE THREAD

**Issue by EkjotKaur** [pankajkumarbij/easy-job-intern#414]
Form for create online training

@pankajkumarbij  please assign me this issue.

**Comment by pankajkumarbij** [comment]
@EkjotKaur We have not provided any training through this plateform.

**Comment by EkjotKaur** [comment]
The frontend of the website had links for Online training that's why created it.

**Comment by pankajkumarbij** [comment]
@EkjotKaur yes its made by someone when home page is created.
