### ISSUE TITLE
create a company model

### ISSUE THREAD

**Issue by mitalirs** [pankajkumarbij/easy-job-intern#428]
## Is your feature request related to a problem? Please describe.
currently, there is no company model to check the authenticity of employers, (any employer can create his/her profile with a company name without the consent of the company)

## Describe the solution you'd like
a 'company' model with fields like:
1. name
2. no of employees
3. registered employees
4. tags (actively hiring, funded, growing fast, etc)
5. tagline/motto
6. investment stage
7. tokens
8. email
9. password

- adding this will also give students an idea about the company they will be working for 
- and employers will be able to add company name on their profile only if it is approved by the company (ie if they are registered as an employee in that company)

I wish to work on the backend part

**Comment by pankajkumarbij** [comment]
@mitalirs You can make backend for company profile that make by an employer.

**Comment by pankajkumarbij** [comment]
@mitalirs You can open an issue regarding adding checks while sign up so that no 2 employers with same company name exist that you describe in the closed issue.
