### ISSUE TITLE
add a login+signin route for company

### ISSUE THREAD

**Issue by mitalirs** [pankajkumarbij/easy-job-intern#429]
## Is your feature request related to a problem? Please describe.
no way for a company to sign in/login

## Describe the solution you'd like
add proper routes to the backend controller file of the company

**Comment by pankajkumarbij** [comment]
Employer is only responsible for that company you can add functionality to that employer to make profile of that company.

There is no separate login or signup for any company.

**Comment by mitalirs** [comment]
> Employer is only responsible for that company you can add functionality to that employer to make profile of that company.
> 
> There is no separate login or signup for any company.

Alright, I misunderstood the idea, I thought a company can have more than employees who can create job openings and so I believed that they have to be registered with the company
Sorry for the confusion

Also according to this 2 employers cannot sign-up with the same company name, right? so @pankajkumarbij, will it be okay if I create a new issue regarding adding checks while sign up so that no 2 employers with same company name exist?

**Comment by pankajkumarbij** [comment]
> > Employer is only responsible for that company you can add functionality to that employer to make profile of that company.
> > There is no separate login or signup for any company.
> 
> Alright, I misunderstood the idea, I thought a company can have more than employees who can create job openings and so I believed that they have to be registered with the company
> Sorry for the confusion
> 
> Also according to this 2 employers cannot sign-up with the same company name, right? so @pankajkumarbij, will it be okay if I create a new issue regarding adding checks while sign up so that no 2 employers with same company name exist?

@mitalirs You can create an issue regarding adding checks while sign up so that no 2 employers with the same company name exist.

Thanks for making this project amazing.
