### ISSUE TITLE
Add contributors in the readme.md

### ISSUE THREAD

**Issue by pankajkumarbij** [pankajkumarbij/easy-job-intern#5]
Add contributors in the readme.md file.

**Comment by 96RadhikaJadhav** [comment]
@pankajkumarbij  From where to get contributors name?

**Comment by pankajkumarbij** [comment]
> @pankajkumarbij From where to get contributors name?

@96RadhikaJadhav tries to do it dynamically So next time contributor name automatically update.
If you can not do dynamically than no issue do it static.
here you can see all contributors :
https://github.com/pankajkumarbij/easy-job-intern/graphs/contributors

**Comment by 96RadhikaJadhav** [comment]
@pankajkumarbij  For now I can add manually. Going forward I guess we can implement this as a check in the PR template, so while creating PR everyone can add their name in the list.

**Comment by pankajkumarbij** [comment]
> name

@96RadhikaJadhav Good idea.

**Comment by pankajkumarbij** [comment]
@96RadhikaJadhav Thanks for your contribution.
