### ISSUE TITLE
Integrate Login and Signup page for students with database.

### ISSUE THREAD

**Issue by pankajkumarbij** [pankajkumarbij/easy-job-intern#50]
Integrate Login and Signup page for students with database

Use mongoose(MongoDB) with Node.js(express.js) for store user details. (use local system MongoDB for store means don't use any online platform).

**Comment by sparshsharma2510** [comment]
Hey, I would love to contribute to this. Please assign it to me

**Comment by sparshsharma2510** [comment]
> Hey, I would love to contribute to this. Please assign it to me

Also, can you please suggest me ways to get started with it

**Comment by pankajkumarbij** [comment]
@sparshsharma2510 Go ahead.
Read contributing.md and readme.md file to understand how to run the project and make a PR.

**Comment by srk224** [comment]
Hey. I would like to work on this issue? Is their a discord or any other medium to communicate well?

**Comment by Esha-Sherring** [comment]
I would like to work on this issue

**Comment by pankajkumarbij** [comment]
@srk224 and @Esha-Sherring this issue is already assigned.
You can find the discord channel in the readme file.
