### ISSUE TITLE
modify create job route

### ISSUE THREAD

**Issue by mitalirs** [pankajkumarbij/easy-job-intern#519]
## Is your feature request related to a problem? Please describe.
while creating a job, the job's companyName field should be the same as the company name field of the employer

## Describe the solution you'd like
add some code to fix the issue

**Comment by pankajkumarbij** [comment]
@mitalirs If you solve one more issue your rank can be in the top 25 contributors.
You can solve the issue related to the job form that I have opened at level3.

**Comment by mitalirs** [comment]
Actually, I am working on other issues and I also don't have the relevant frontend knowledge

**Comment by pankajkumarbij** [comment]
> Actually, I am working on other issues and I also don't have the relevant frontend knowledge

keep it up bro you are already in the top 25.

DM me after completion the program on discord.
