### ISSUE TITLE
Connect database with contact us page.

### ISSUE THREAD

**Issue by pankajkumarbij** [pankajkumarbij/easy-job-intern#55]
Integrate database with contact us page.

Use ```fetch``` in react for post and get data.

Backend is already present in the server(you can update backend code also if you want).

All mongoose-related schemas should be in the models folder in the server and route in the routes folder.

**Comment by kartikpuri99** [comment]
please assign this issue to me.Can i use axios for request instead of fetch?

**Comment by pankajkumarbij** [comment]
@kartikpuri99 one issue can be assigned at a time.

**Comment by pankajkumarbij** [comment]
@kartikpuri99 Now you can work on this issue but you should use the fetch method only.

**Comment by kartikpuri99** [comment]
Please review my PR I have completed it.

**Comment by kartikpuri99** [comment]
Please check now
