### ISSUE TITLE
Add a remember me option in login page

### ISSUE THREAD

**Issue by Ayonijakaushik19** [pankajkumarbij/easy-job-intern#553]
## Is your feature request related to a problem? Please describe.
-Sometimes it becomes hectic to type username and password often to log in so we can have remembered me option which saves the login information for a particular period, this enables the user to login easily and it also enhances the user experience

## Additional context
Add any other context about the feature request here.

**Comment by Ayonijakaushik19** [comment]
Hi @pankajkumarbij, Please assign this to me.

**Comment by pankajkumarbij** [comment]
@Ayonijakaushik19 Go ahead

**Comment by pankajkumarbij** [comment]
@Ayonijakaushik19 are you working on it?
