### ISSUE TITLE
add some more badges to readme

### ISSUE THREAD

**Issue by Umesh-01** [pankajkumarbij/easy-job-intern#554]
## Description
add some more badges to the top of readme.md file, since the badges will be colorful and more attractive at the top of README.md file than the text the users will like it and after linking the badges it will also help them to navigate to different sections/ webpages like PRs, issues, contributors, etc.

## Describe the solution you'd like

![image](https://user-images.githubusercontent.com/83420185/124013207-a733a680-d9ff-11eb-8e10-b88c23689fba.png)

I will add some more badges at the top and also will add links related to them so that the README.md file will look more interactive and awesome.

### Work under/as

- [x] LGMSOC
- [ ] Contributor

**Comment by Umesh-01** [comment]
@pankajkumarbij Should I work on this issue??

**Comment by pankajkumarbij** [comment]
@Umesh-01  go-ahead

**Comment by pankajkumarbij** [comment]
@Umesh-01 you can start working on it and make a PR, I will add labels later.
