### ISSUE TITLE
alignment of the first line in "Internship By Industry, location,stream and training"

### ISSUE THREAD

**Issue by akshatvirmani** [pankajkumarbij/easy-job-intern#555]
## Is your feature request related to a problem? Please describe.
Alignment of the first line in "Internship By Industry, location,stream and training"

## Describe the solution you'd like
before:
![image](https://user-images.githubusercontent.com/77536248/124303804-7e86ea80-db80-11eb-8a7e-79692b956d3b.png)

after:
![image](https://user-images.githubusercontent.com/77536248/124303657-526b6980-db80-11eb-849c-781f84503c59.png)

**Comment by pankajkumarbij** [comment]
@akshatvirmani  Go ahead
