### ISSUE TITLE
Changing the location name

### ISSUE THREAD

**Issue by akshatvirmani** [pankajkumarbij/easy-job-intern#558]
## Describe the bug
Changing the name of the location in the last line

## Additional context
The last location name is "India". Should replace it with another location in India.
![image](https://user-images.githubusercontent.com/77536248/124354225-9fa31600-dc28-11eb-912b-a1b7fe1037b2.png)

**Comment by pankajkumarbij** [comment]
@akshatvirmani Go ahead.
