### ISSUE TITLE
Integrate database with login and signup pages for students.

### ISSUE THREAD

**Issue by pankajkumarbij** [pankajkumarbij/easy-job-intern#56]
Integrate database with login and signup pages for students.

Use fetch in react for post and get data.

All mongoose-related schemas should be in the models folder in the server and route in the routes folder.

code formatting should be nice.

**Comment by hrushikesh-git** [comment]
hey @pankajkumarbij  I would like to work on this issues as GSSOC'21 participant please assign this issue to me

**Comment by pankajkumarbij** [comment]
@hrushikesh-git Go ahead

**Comment by hrushikesh-git** [comment]
@pankajkumarbij thank you for assigning this issue will start working on it and get back to you

**Comment by hrushikesh-git** [comment]
Do I have to create models and for the student? If yes can you please list out me the required fields

**Comment by pankajkumarbij** [comment]
@hrushikesh-git you can explore the front end part of the signup ad login form for students(all fields are required).

**Comment by hrushikesh-git** [comment]
Okay thanks

**Comment by hrushikesh-git** [comment]
hey @pankajkumarbij  created modals, route and integrated with react frontend please check and suggest changes if any
