### ISSUE TITLE
Improving footer

### ISSUE THREAD

**Issue by akshatvirmani** [pankajkumarbij/easy-job-intern#569]
## Is your feature request related to a problem? Please describe.
No

## Describe the solution you'd like
I would like to improve the footer of the home page.

**Comment by akshatvirmani** [comment]
Should I work on this issue Sir?

**Comment by pankajkumarbij** [comment]
@akshatvirmani  ok go ahead.

**Comment by pankajkumarbij** [comment]
@akshatvirmani I think this footer is fine or you are working?
If not working I will close this issue and assign you another privacy policy page design issue.

**Comment by akshatvirmani** [comment]
Sir, I have made the pr for footer

**Comment by pankajkumarbij** [comment]
@akshatvirmani Yellow color good than white with black.
ok, Work with another issue if you want.
