### ISSUE TITLE
Improve Privacy and Policy page design.

### ISSUE THREAD

**Issue by pankajkumarbij** [pankajkumarbij/easy-job-intern#572]
Improve Privacy and Policy page design.
Privacy and Policy page link in the footer of the website.

Use React Bootstrap and improve the design in dark mode as other pages of the website.

**Comment by akshatvirmani** [comment]
I would like to work on this issue. Kindly assign me.

**Comment by pankajkumarbij** [comment]
@akshatvirmani Only one issue can be assigned at a time so which issue do you want to solve?
I think the footer is nice no need to improve?

**Comment by gaurii06** [comment]
Gaurika

**Comment by pankajkumarbij** [comment]
@gaurii06 Go ahead
