### ISSUE TITLE
Improve Validation of Student Sign up and Login Page

### ISSUE THREAD

**Issue by pankajkumarbij** [pankajkumarbij/easy-job-intern#575]
Improve Validation of Student Sign up and Login Page:-

Name Should not have any validation related to minimum length only this field is required.

password and confirm password should have validation error below the field not horizontal with the fields.

Check other validations too.

**Comment by akshatvirmani** [comment]
I would like to work on this issue. Kindly assign me.

**Comment by akshatvirmani** [comment]
Can I work on this issue now?

**Comment by pankajkumarbij** [comment]
@akshatvirmani yes go ahead
