### ISSUE TITLE
Connect about us page link with about us button in footer

### ISSUE THREAD

**Issue by pankajkumarbij** [pankajkumarbij/easy-job-intern#58]
Connect about us page link with about us in the footer.

Make sure the page should not be refresh use react-router dom.

**Comment by kartikpuri99** [comment]
Please assign this issue to me

**Comment by pankajkumarbij** [comment]
@kartikpuri99 you commented in two issues which one you want to contribute because only one issue can be assigned at a time.

**Comment by kartikpuri99** [comment]
i can do this first please assign this first and if someone didnot take that one i would take it after i have completed this one

**Comment by kartikpuri99** [comment]
Please review my PR.I have connected the code for connecting the footer link to about us page and have also refactored the code of react-router as there was code repetition in both navbar and footer i have called the browser router in app.js to avoid code repetition

**Comment by pankajkumarbij** [comment]
@kartikpuri99 Very nice work.
