### ISSUE TITLE
Signup Bug fix - LGMSoC

### ISSUE THREAD

**Issue by AVS18** [pankajkumarbij/easy-job-intern#581]
The Password and Confirm password in the student registration is showing the text at the side of the text box instead of new line

## To Reproduce
1.  Check the password and confirm password box
2.  Add a break tag at the end of box
3. Do this for signup pages of both employer and student

## Current state of design
![image](https://user-images.githubusercontent.com/47914143/127768127-4d31d3b9-4e8d-4c75-a9cf-4c49dc8ecc40.png)

**Comment by pankajkumarbij** [comment]
@AVS18 already opened the issue.
