### ISSUE TITLE
Connect contact us page link with contact us button in the footer.

### ISSUE THREAD

**Issue by pankajkumarbij** [pankajkumarbij/easy-job-intern#59]
Connect contact us page link with contact us button in the footer.

Make sure the page should not be refresh use react-router-dom.

**Comment by aishwarya0816** [comment]
@pankajkumarbij Please assign this issue to me. I am a GSSOC'21 participant.

**Comment by pankajkumarbij** [comment]
@aishwarya0816 Only one issue can be assigned at a time.
make PR for the already assigned issue then I will assign another issue.

**Comment by arbazalam01** [comment]
can i work on it as a GSSOC21 participant

**Comment by pankajkumarbij** [comment]
> can i work on it as a GSSOC21 participant

@arbazalam01 Go ahead

**Comment by pankajkumarbij** [comment]
@arbazalam01 Now the project is updated because I have merged a PR.
You can easily resolve the issue now.
Pull all the changes from the master branch and then try to contribute.

**Comment by pankajkumarbij** [comment]
@arbazalam01 are you working on this issue?

**Comment by arbazalam01** [comment]
can you please check the PR
