### ISSUE TITLE
Connect  privacy policy page link with privacy policy button in the footer.

### ISSUE THREAD

**Issue by pankajkumarbij** [pankajkumarbij/easy-job-intern#60]
Connect privacy policy page link with privacy policy button in the footer.

Make sure the page should not be refresh use react-router-dom.

**Comment by aishwarya0816** [comment]
@pankajkumarbij Please assign this issue to me. I am a GSSOC'21 participant.

**Comment by pankajkumarbij** [comment]
@aishwarya0816 Go ahead

**Comment by pankajkumarbij** [comment]
@aishwarya0816  Now the project is updated because I have merged a PR.
You can easily resolve the issue now.
Pull all the changes from the master branch and then try to contribute.

**Comment by hrushikesh-git** [comment]
@pankajkumarbij  can you assign this issue to me I am gssoc participant
