### ISSUE TITLE
Connect terms and condition page link with terms and condition button in the footer.

### ISSUE THREAD

**Issue by pankajkumarbij** [pankajkumarbij/easy-job-intern#61]
Connect terms and condition page link with terms and condition button in the footer.

Make sure the page should not be refresh use react-router-dom.

**Comment by aishwarya0816** [comment]
@pankajkumarbij Please assign this issue to me. I am a GSSOC'21 participant.

**Comment by pankajkumarbij** [comment]
@aishwarya0816 Only one issue can be assigned at a time. 
make PR for the already assigned issue then I will assign another issue.

**Comment by kartikpuri99** [comment]
@pankajkumarbij Please assign it to me.

**Comment by sakshigoel19** [comment]
@pankajkumarbij I am a GSSOC'21 participant. Please assign it to me.

**Comment by pankajkumarbij** [comment]
@kartikpuri99  Go ahead

**Comment by pankajkumarbij** [comment]
Issues assigned as based on FCFS manner.
