### ISSUE TITLE
improving the Home page design and making it responsive

### ISSUE THREAD

**Issue by sukhpreet-singh1** [pankajkumarbij/easy-job-intern#66]
i would like to solve this issue under GSSOC21 as i had already used your project i found home page some field to be changed.

**Comment by pankajkumarbij** [comment]
> i would like to solve this issue under GSSOC21 as i had already used your project i found home page some field to be changed.

Go ahead

**Comment by pankajkumarbij** [comment]
@sukhpreet-singh1 any update?

**Comment by sukhpreet-singh1** [comment]
yes i will make PR tomorrow

**Comment by pankajkumarbij** [comment]
@sukhpreet-singh1 ok

**Comment by pankajkumarbij** [comment]
@sukhpreet-singh1 any update?

**Comment by sukhpreet-singh1** [comment]
i had created but it was having responsive issue it was now looking good on phone now changing it further.

**Comment by pankajkumarbij** [comment]
@sukhpreet-singh1 Keep it up

**Comment by pankajkumarbij** [comment]
@sukhpreet-singh1 After you forked the project there are many PR merged then you should pull all the changes and check once that all things are working or not before making PR.

**Comment by pankajkumarbij** [comment]
@sukhpreet-singh1 any update?

**Comment by pankajkumarbij** [comment]
@sukhpreet-singh1 are you working on it?

**Comment by pankajkumarbij** [comment]
@sukhpreet-singh1 I will close this issue tomorrow because you are not giving any update about it so I will consider that you are not working on this issue.
