### ISSUE TITLE
Login and signup endpoint

### ISSUE THREAD

**Issue by asi309** [pankajkumarbij/easy-job-intern#67]
## Create Login and Signup endpoint for backend.

<ul>
  <li>These endpoints are to be used for connecting frontend to backend api</li>
  <li>use simple names like 'login' and 'signup</li>
  <li>create model for user based on fields available in signup page (Check frontend). Model should be in models folder.</li>
</ul>

**Comment by pankajkumarbij** [comment]
@asi309 Nice issue but please check issue #56 
I think both issues have conflict.

**Comment by pankajkumarbij** [comment]
@asi309 this issue is nicely explained but the issue is already opened.
you can comment under that issue for other functionalities that you want.
Thank you.

**Comment by asi309** [comment]
@pankajkumarbij Closing this issue and commenting under #56 .
