### ISSUE TITLE
We can insert Alert messages 

### ISSUE THREAD

**Issue by hrushikesh-git** [pankajkumarbij/easy-job-intern#72]
For the instruction of client, For ex:- After Login or signup a popup will came show that signup is successfull or if any error
![alert](https://user-images.githubusercontent.com/65762074/110794153-73d7db00-829b-11eb-8573-6ceb970d7df9.png)

**Comment by hrushikesh-git** [comment]
Please @pankajkumarbij  have a look into this and if you agree please assign this to me GSSOC'21

**Comment by pankajkumarbij** [comment]
@hrushikesh-git GO ahead

**Comment by hrushikesh-git** [comment]
Thanks @pankajkumarbij
