### ISSUE TITLE
Add required files and folders in .gitignore for frontend and backend both.

### ISSUE THREAD

**Issue by pankajkumarbij** [pankajkumarbij/easy-job-intern#74]
Add required files and folders in .gitignore for frontend and backend both.

ex: node_modules, package-lock.json, .eslintcache etc.

you can search about it which files and folders should be in .gitignore.

**Comment by srk224** [comment]
Hey.
Can I work on this ..I have some experience in web-dev and I think ill be able to do it.
Can you assign it to me ?

**Comment by aishwarya0816** [comment]
I would like to do this. Please assign it to me

**Comment by pankajkumarbij** [comment]
@srk224 Go ahead

**Comment by pankajkumarbij** [comment]
@aishwarya0816 You can work on issue #76 
Because issues are assigned based on FCFS manner.

**Comment by pankajkumarbij** [comment]
> @aishwarya0816 You can work on issue #76
> Because issues are assigned based on FCFS manner.

@aishwarya0816, please comment below on issue #76  so I can able to assign you.

**Comment by srk224** [comment]
Done!! and created the PR.
Please check it out
@pankajkumarbij
