### ISSUE TITLE
Handling Contact Us Form submission using Formspree API

### ISSUE THREAD

**Issue by healer9** [pankajkumarbij/easy-job-intern#75]
## Is your feature request related to a problem? Please describe.
Creating Contact Us Form using Formspree.

## Describe the solution you'd like
I'll create contact-us form UI using React JS on the frontend and send the data of the user to the project admin email through Formspree API.

I'm going to edit the contact-us.js file and update it using react functional component i.e, Hooks. After that, on submission of the contact-us form, I'll send the user data to the project's admin email, using Formspree API.

## Additional context
By using Formspree we don't require to connect our frontend contact-us form to the backend to store the data in the database.

**Comment by healer9** [comment]
@pankajkumarbij assign this issue to me and provide me the fields you want to be in the contact-us form.

You have to create an account on the Formspree website and you also have to generate a token (secret). So that formspree API can authenticate through it. 

Provide me the email where I've to send the data on submission of the form and the generated token.

**Comment by pankajkumarbij** [comment]
@healer9 Go ahead

**Comment by pankajkumarbij** [comment]
> @pankajkumarbij assign this issue to me and provide me the fields you want to be in the contact-us form.
> 
> You have to create an account on the Formspree website and you also have to generate a token (secret). So that formspree API can authenticate through it.
> 
> Provide me the email where I've to send the data on submission of the form and the generated token.

Contact us form fields: Name, Email, Mobile no(optional), message.

Can you work with your email id and token as of now because it is easy to check that email is working or not with the sent msg.

After that when work is ready to make a PR then I will give you a token and email id or you can use the .env file to configuring secrete key and email id.

If you want to work only with my account then I will provide you tomorrow.

**Comment by healer9** [comment]
![contact-us](https://user-images.githubusercontent.com/60239025/110814281-4f85f980-82af-11eb-867b-29301d40f28c.png)
 
## Do I have to change the current UI or its ok?

## Or do I have to implement only the submission handling part of the contact-us form?

**Comment by pankajkumarbij** [comment]
@healer9 If you can implement a better UI for the contact us page then it is well and good otherwise you can work with the submission handling part only.

**Comment by healer9** [comment]
@pankajkumarbij  Can I use Axios (npm) for posting data to the formspree server?

**Comment by pankajkumarbij** [comment]
@healer9 you can use axios but try to use ```fetch``` because all other backend part is use fetch method for request, so its good to use same method for all.

**Comment by healer9** [comment]
> > @pankajkumarbij assign this issue to me and provide me the fields you want to be in the contact-us form.
> > You have to create an account on the Formspree website and you also have to generate a token (secret). So that formspree API can authenticate through it.
> > Provide me the email where I've to send the data on submission of the form and the generated token.
> 
> Contact us form fields: Name, Email, Mobile no(optional), message.
> 
> Can you work with your email id and token as of now because it is easy to check that email is working or not with the sent msg.
> 
> After that when work is ready to make a PR then I will give you a token and email id or you can use the .env file to configuring secrete key and email id.
> 
> If you want to work only with my account then I will provide you tomorrow.

@pankajkumarbij  
### I'm ready to make a pull request. 
I check my work and the form is also getting submitted successfully. And the contact form data is also sent to the email address(Currently on my email) successfully. 🙂

**Comment by pankajkumarbij** [comment]
@healer9 I will provide you details tomorrow after create account, you can make PR after I will send you details email and token secret key.

**Comment by pankajkumarbij** [comment]
@healer9 After login which type of project I need to create?

Please tell all the steps for generating the key and all.

**Comment by healer9** [comment]
# Steps to follow:

- First, you should verify your email address through which you have been registered.
- Click on create a "New project" button.
- Enter your "Project Name" in the Project Name field.
- And then click the "Create Project" button.

![project-name](https://user-images.githubusercontent.com/60239025/110895793-5436c600-8320-11eb-8c2a-6ccd16560370.png)

- Click on get started.

![get-started](https://user-images.githubusercontent.com/60239025/110896042-c8716980-8320-11eb-8d24-577bbedc3fb1.png)

- In "Form Name" enter "Contact Us".
- In "Project Name" it will automatically fill it.
- In the "Send Emails to field" enter the email where you want to send the submissions.
- And then click the "Create Form" button. 

![create-form](https://user-images.githubusercontent.com/60239025/110896775-42562280-8322-11eb-9ec9-e9130db25679.png)

- After that, you get the end-point of the formspree API with the token.

![end-point](https://user-images.githubusercontent.com/60239025/110896854-6f0a3a00-8322-11eb-99cb-ed5c4671b82d.png)

- Make all settings as mentioned below.

![settings](https://user-images.githubusercontent.com/60239025/110896919-8a754500-8322-11eb-9c60-fbf43954ea5c.png)

- To see all your submissions

![submissions](https://user-images.githubusercontent.com/60239025/110897376-59494480-8323-11eb-8d69-0f0624702d9f.png)

- Submission Dashboard

![all-submissions](https://user-images.githubusercontent.com/60239025/110897407-65350680-8323-11eb-822b-8277c10dc3da.png)

## I think this will help you @pankajkumarbij .

**Comment by pankajkumarbij** [comment]
@healer9 Nice Explanation I understood and created API successfully But I can't give API here in the comment because it will visible to the public.
Make a PR, I will chnage API there.
You tell me where I should chnage API.
Please remove your API details before making a PR.

**Comment by healer9** [comment]
Ok I'll.

@pankajkumarbij  Can you please update the `GSSOC` label to `GSSOC21`.

**Comment by pankajkumarbij** [comment]
@healer9 I have updated the label name.
