### ISSUE TITLE
Make footer more responsive

### ISSUE THREAD

**Issue by pankajkumarbij** [pankajkumarbij/easy-job-intern#76]
Make the footer more responsive that all the fields that look on the full screen also should be view in mobile view or any view.

**Comment by pankajkumarbij** [comment]
@aishwarya0816 Go ahead

**Comment by aishwarya0816** [comment]
I want to work on this issue

**Comment by richakumari19** [comment]
I'm GSSOC'21 participant. wanted to work on this issue. Can you please assign me this issue?

**Comment by pankajkumarbij** [comment]
@rk05-lenavo This issue is already assigned.

**Comment by pankajkumarbij** [comment]
@aishwarya0816 any update?

**Comment by aishwarya0816** [comment]
> @aishwarya0816 any update?

I am on it. Now I'm doing it using css grid. Will that be okay? 
Also can you clarify once exactly how is it expected. Like when you say responsive:

1) do you want it to look similar in mobile view (like to how it is in the laptop view.)
2) or can I rearrange it. So as every thing will be visible in any view but in different arrangement (css grid). In this case the 4 columns in footer in laptop will rearrange themselves one below another in mobile view.
Sorry for such a long text 😅
@pankajkumarbij

**Comment by pankajkumarbij** [comment]
@aishwarya0816 I want the 2nd option: Everything will be visible in any view but in a different arrangement (CSS grid). In this case, the 4 columns in the footer in the laptop will rearrange themselves one below another in mobile view.

You can use CSS grid.

**Comment by aishwarya0816** [comment]
@pankajkumarbij Okay I will do it asap
