### ISSUE TITLE
Creating signout route and write it's logic and Connect with react

### ISSUE THREAD

**Issue by hrushikesh-git** [pankajkumarbij/easy-job-intern#79]
## Describe the bug
After Logging in we can't make a logout request we have to manually clear data

## Solution
Create a signout Route at the backend and integrate it with React Front-End and Create a bottom in NavBar using Conditional rendering

**Comment by hrushikesh-git** [comment]
@pankajkumarbij hey if you agree let me please work on it and assign it to me thank you

**Comment by pankajkumarbij** [comment]
@hrushikesh-git Go ahead

After login a student there should be an email or name of the student in the navbar and a logout button instead of sign-in and sign-up buttons.

**Comment by pankajkumarbij** [comment]
@hrushikesh-git when you have done this issue's work?

**Comment by hrushikesh-git** [comment]
Hey @pankajkumarbij  sorry due to a family problem I couldn't do this but soon within a day or two I will finish it and merge the code. Really sorry for the delay

**Comment by pankajkumarbij** [comment]
@hrushikesh-git No problem, I have just asked about the update.
You can do it whenever you are free.
