### ISSUE TITLE
Enhancing the UI(readme.md)

### ISSUE THREAD

**Issue by aditisneh** [pankajkumarbij/easy-job-intern#80]
Basically , we need to add an attractive poster so that people get to see our project.  A banner for mentors involved. We can also add a gif explaining how our objective works, this will convey the message very easily and attract the crowd.

**Comment by aditisneh** [comment]
![easy-job-intern](https://user-images.githubusercontent.com/56735634/110901690-b399d380-832a-11eb-9f04-764dcf7e3b40.png)
This can be our logo/banner at top.
Please assign this and add gssoc21 and level tags.

**Comment by srk224** [comment]
I would like to work on this .
Please assign this to me

**Comment by pankajkumarbij** [comment]
@aditisneh Go ahead

**Comment by aditisneh** [comment]
@pankajkumarbij okay thanks

**Comment by richakumari19** [comment]
I'm a GSSOC'21 participant kindly assign me this issue. I would love to work in this.

**Comment by pankajkumarbij** [comment]
@rk05-lenavo This issue is already assigned, one issue can be assigned to only one at a time.
