### ISSUE TITLE
Create a contact us form on the footer.

### ISSUE THREAD

**Issue by abhinav5481** [pankajkumarbij/easy-job-intern#84]
## Is your feature request related to a problem? Please describe.
It would be better if the footer will a short `contact us` form which will have email & message as input.

## Describe the solution you'd like
A form with the above-mentioned fields.

**Comment by abhinav5481** [comment]
hi @pankajkumarbij 
I would like to work on this issue as part of Gssoc'21. Could you please assign me this issue?

**Comment by pankajkumarbij** [comment]
@abhinav5481 you can do that after some time because some backend work related to this is ongoing.
I put this is on hold at this time.

**Comment by abhinav5481** [comment]
No problem, then, please assign this task to me when the ongoing backend work gets completed.

**Comment by pankajkumarbij** [comment]
@abhinav5481 Sure

**Comment by pankajkumarbij** [comment]
@abhinav5481 We not need to put the contact us page in the footer because there we require other things.

Thanks for opening an issue.
