### ISSUE TITLE
Sending mail using nodemailer when a new user signs up.

### ISSUE THREAD

**Issue by udaymittal7** [pankajkumarbij/easy-job-intern#86]
I would like to add the functionality of sending a mail whenever a new user signs up to the app.
I am a participant of GSSOC'21.

If you find it relevant, please assign me to it and add the necessary tags.

**Comment by palashgupta98** [comment]
Hi @udaymittal7 
Please use https://sendgrid.com/ which exposes a node package for same

**Comment by udaymittal7** [comment]
@palashgdev Yes, as service in nodemailer, I was gonna use gmail or sendgrid as per the instructions. So, now  I will be using sendgrid as the service. Thank you. Please add the relevant tags.

**Comment by palashgupta98** [comment]
@pankajkumarbij can you please add relevant tags here

**Comment by palashgupta98** [comment]
also @pankajkumarbij make sure the address is verified

**Comment by udaymittal7** [comment]
I have created a PR with #91 tag on it. Please review it @palashgdev @pankajkumarbij.

**Comment by pankajkumarbij** [comment]
@palashgdev please review the PR related to this issue.
