### ISSUE TITLE
About Page 

### ISSUE THREAD

**Issue by gokulkannan7** [pankajkumarbij/easy-job-intern#88]
I would like to add content in the about section of the website based on what you want to have there.
I am a participant in GSSOC'21. If you find it relevant, please assign me to it and add the necessary tags

**Comment by pankajkumarbij** [comment]
@gokulkannan7 You can work on this issue I will tell you that what things require to be in about us.

**Comment by gokulkannan7** [comment]
@pankajkumarbij  Yeah, sure

**Comment by pankajkumarbij** [comment]
@gokulkannan7 We want to make this website for the purpose of connecting students to companies so that companies can open applications and students can apply in multiple companies with the same profile.

You can explore some job and internship websites and put about content accordingly.

**Comment by abhinav5481** [comment]
Hi @pankajkumarbij 
I would like to work on this issue as part of CrossWoc'21. Please assign it to me.

**Comment by pankajkumarbij** [comment]
@abhinav5481 I have messaged him tomorrow I think He is working on it.

**Comment by abhinav5481** [comment]
I think he is working for GSSOC'21. But I want to work on it for CrossWoc'21. Can you simultaneously assign it to me user crosswoc label?

**Comment by pankajkumarbij** [comment]
@abhinav5481 But only one contributor can work with one issue.
You can work on issue #36
Comment under that issue if you want to work on that issue.
I will assign you.

**Comment by abhinav5481** [comment]
Commented

**Comment by Ankita297** [comment]
@pankajkumarbij   Can i work on this ?

**Comment by pankajkumarbij** [comment]
@gokulkannan7 are you working on it?

**Comment by pankajkumarbij** [comment]
@Ankita297 Go ahead

**Comment by pankajkumarbij** [comment]
@Ankita297 are you working on it?

**Comment by abhinav5481** [comment]
@pankajkumarbij 
If anyone is not working on it. Please assign it to me.

**Comment by pankajkumarbij** [comment]
@abhinav5481 wait for a reply If she is not working on it I will assign it to you.

**Comment by Ankita297** [comment]
I am working on it @pankajkumarbij

**Comment by Ankita297** [comment]
![Uploading React App - Google Chrome 26-03-2021 12_56_55.png…]()

**Comment by Ankita297** [comment]
![React App - Google Chrome 26-03-2021 12_57_03](https://user-images.githubusercontent.com/67833077/112597196-d0f29580-8e32-11eb-8918-a27090422c6b.png)

**Comment by Ankita297** [comment]
![React App - Google Chrome 26-03-2021 12_56_55](https://user-images.githubusercontent.com/67833077/112597233-df40b180-8e32-11eb-9622-83ce104c60f1.png)

**Comment by Ankita297** [comment]
@pankajkumarbij 
 is this okay or you need some changes . Any other idea or suggestion ?

**Comment by Ankita297** [comment]
@pankajkumarbij  please see .

**Comment by pankajkumarbij** [comment]
@Ankita297 Nice Work but
This project is also for job and intern roles. Companies register here and then open opportunities on our website that feature is not done but we will be done it.

So you can not promote any other website you have to write about our web site only.

Explore some best about us pages on different websites and make it accordingly.

**Comment by pankajkumarbij** [comment]
@Ankita297 You can convert that three columns in Internship, Job, Fresher's Job instead of companies and I will give later the link of job, internship, freshers job page link with buttons you can make PR without the link of buttons.

Add best icons for internship, job, freshers job instead of companies logo and write small content about intern, job, freshers job respectively.

Hope you understand.

If you have any doubt you can ask me.

**Comment by Ankita297** [comment]
So you are asking for like in single row add three columns one of internship ,job and Fresher's jobs 
is it right ? @pankajkumarbij

**Comment by Ankita297** [comment]
also the content  in about section  should i add more ?

**Comment by pankajkumarbij** [comment]
> So you are asking for like in single row add three columns one of internship ,job and Fresher's jobs
> is it right ? @pankajkumarbij

@Ankita297 I want one row that you are already created and that is fine you can update content with a mixture of internship, job, freshers job.

And I want to replace 3 columns that you are created for other compies link with respect to the Internship column, job column, freshers job column.

1 row only + 1 row with 3 columns.

**Comment by Ankita297** [comment]
okay
