### ISSUE TITLE
Improve readme file contributors name with their image.

### ISSUE THREAD

**Issue by pankajkumarbij** [pankajkumarbij/easy-job-intern#9]
Improve readme file contributors' names with their images.

**Comment by sujal111** [comment]
Allow me to work on this issue

**Comment by pankajkumarbij** [comment]
> Allow me to work on this issue

Go ahead

**Comment by pankajkumarbij** [comment]
@sujal111 are you working on this issue?

**Comment by arbazalam01** [comment]
Can i work on this issue

**Comment by pankajkumarbij** [comment]
@arbazalam01 only one issue can assign at a time.

**Comment by pankajkumarbij** [comment]
> Can i work on this issue

@arbazalam01 Now Go ahead

**Comment by vrouilhac** [comment]
Hello, I see that this issue was opened 4 days ago and I suggested you a change if you want to see it. #41
