### ISSUE TITLE
Configure DOTenv

### ISSUE THREAD

**Issue by palashgupta98** [pankajkumarbij/easy-job-intern#90]
## Describe the bug
secrets in an app should be grabbed from an environment variable rather than a hard coded string which is [located here](https://github.com/pankajkumarbij/easy-job-intern/blob/master/server/keys.js)

## Expected behaviour
should grab the variables from .env and should make an assertion that necessary variables are present while starting the app

## Additional context
There should be 3 env file 
1. test
1. production
1. local

**Comment by palashgupta98** [comment]
@pankajkumarbij please add relevant tags for the same so that it will be helpful

**Comment by pankajkumarbij** [comment]
@palashgdev Which level of difficulty I should give to this issue.

**Comment by nandinibansal2000** [comment]
I would like to work on this issue. Kindly assign this issue to me.

**Comment by pankajkumarbij** [comment]
@nandinibansal2000 Go ahead

**Comment by palashgupta98** [comment]
@nandinibansal2000 any bottleneck?
