### ISSUE TITLE
Adding various security features

### ISSUE THREAD

**Issue by udaymittal7** [pankajkumarbij/easy-job-intern#93]
Setting various HTTP headers using helmet
Data sanitization against no SQL injection and XSS
Rate limiter so the server won't get overload
Preventing parameter pollution

If you find it relevant, please assign me.
Please add the relevant GSSOC tags too.

**Comment by pankajkumarbij** [comment]
@udaymittal7 Thanks for opening an issue.

Wait for confirmation after that you can work if confirmed.

**Comment by udaymittal7** [comment]
@pankajkumarbij Okay.

**Comment by pankajkumarbij** [comment]
@udaymittal7 Thanks for opening this issue.
But We do not need this feature at this time.
