### ISSUE TITLE
Sign Up Logic at the backend not working

### ISSUE THREAD

**Issue by kartikpuri99** [pankajkumarbij/easy-job-intern#94]
## Sign Up form backend route not working properly
After filling up the Signup/register form the user is not able to register and his data is not stored in the database.It shows the following error

![image](https://user-images.githubusercontent.com/52126579/111059495-21c1d000-84bc-11eb-8a47-cb4011cb9673.png)

Please assign this issue to me and allow me to fix it.

**Comment by pankajkumarbij** [comment]
@kartikpuri99 it is not an error, first we should make a .env file configuration but that is not required at this time so I have commented on all those things.

Now you can pull all the changes and check it will work.

**Comment by kartikpuri99** [comment]
It will work now but now the email will not be sent to a user when new user signs up .The error was because of the name conflict as the function email and the variable coming from req.body had the same name.

**Comment by pankajkumarbij** [comment]
> same

Yeah, there is a name conflict but now we do not need to send the mail.
Thanks for finding an issue.
