### ISSUE TITLE
Contact Us Form Validation 

### ISSUE THREAD

**Issue by kernal053** [pankajkumarbij/easy-job-intern#96]
## Describe the bug
There are multiple validation issues while filling up contact us form.
- First and Last name can be even limited to single letter word( Thus doesn't provide proper identity of user).
- Email validation is checked when user click on submit button( It should be checked while filling up that field).
- Mobile No. can even be less than 10 character.
- Message field character length is not set.

## Expected behavior
Error message should be display below respective field whenever a validation fails. 
- First and Last name can be made to have length of at least 3 characters.
- Email validation can be checked while user is filling up that field.
- Mobile No. can be set to limit of at least 10 character.
- Message field character length can be set to minimum 10 characters.

## Additional context
Please, can any mentor let me contribute to this issue with proper label ? They can also share any further requirement for the issue . Let me know so that I can start working on it.

**Comment by pankajkumarbij** [comment]
@kernal053 Go ahead

**Comment by abhinav5481** [comment]
Hi @pankajkumarbij 
I would like to work on it under CrossWoc'21. Could you please assign it to me?

**Comment by pankajkumarbij** [comment]
@kernal053 Are you working on this issue?

**Comment by kernal053** [comment]
Yes @pankajkumarbij , I will send PR by tomorrow.

**Comment by pankajkumarbij** [comment]
@kernal053 Ok Keep it up.
