### ISSUE TITLE
login  and sign-up form validation for students.

### ISSUE THREAD

**Issue by pankajkumarbij** [pankajkumarbij/easy-job-intern#97]
Login and Sign-up form validation for students.

Use a proper validation method if the user does not enter valid field data then it should give an error msg in a proper format.

**Comment by kartikpuri99** [comment]
Please assign this issue to me.

**Comment by abhishek96k** [comment]
Hey @pankajkumarbij  I would like to work on this issue.  As part of `gssoc` please assign me.

**Comment by pankajkumarbij** [comment]
@kartikpuri99 Go ahead.

**Comment by pankajkumarbij** [comment]
> Hey @pankajkumarbij I would like to work on this issue. As part of `gssoc` please assign me.

One issue can be assigned to one person at a time and issues assigned based on FCFS.

**Comment by kartikpuri99** [comment]
Please review my PR.I have added form validation using custom validator to both login and signup form and have also created a generalized function for checking form validation which can be used in other forms too.Also the form button would be disabled till the time all inputs are validated
