### ISSUE TITLE
Student profile builder form

### ISSUE THREAD

**Issue by pankajkumarbij** [pankajkumarbij/easy-job-intern#98]
Student profile builder form where user can make own profile after login.

You need to make a front-end form only for all the given sections.

- Student Address
- Github Link
- Linkedin Link
- Other Profile Link (Codechef, Portfolio, any hackathon/coding website, etc) 
- Education (College/School name, Stream/Branch, Start Date, End Date, Performance Scale(Optional): CGPA/Percentage, etc, Performance(Optional), Status: pursuing/completed).
- Experience (Company/Organization name, Title, Start Date, End Date, Employment type, Location, Description (Optional))
- Projects (Project Name, Project Link(optional), Start Date, End Date, Description (Optional))
- Skills (Skills like Java, C++, etc.)
- Training/Courses (Coaching/Organization name, Title, Start Date, End Date, Location, Description (Optional))
- Achievements
- Other

All the above fields except Student Address, Github Link, Linkedin Link all other fields must be dynamic means a student can add any number of educations, skills, etc.

Design best-standered form using react-bootstrap.
You need to design the front-end part only.
After login a student there should be a button in the navbar to build own profile.

**Comment by abhishek96k** [comment]
Hey @pankajkumarbij  I would like to work on this issue. Please assign this issue to me.

**Comment by pankajkumarbij** [comment]
@abhishek96k Go ahead

**Comment by srk224** [comment]
Hey , if @abhishek96k is not able to do it. Can you assign it to me?

**Comment by pankajkumarbij** [comment]
@srk224 Wait for some days I think he is trying.

**Comment by pankajkumarbij** [comment]
@abhishek96k are you working on this issue?

**Comment by pankajkumarbij** [comment]
@srk224 Go ahead.

**Comment by srk224** [comment]
@pankajkumarbij I am on it.

**Comment by Jassi10000-zz** [comment]
@pankajkumarbij Being a GSSOC'21 Participant , I would also like to try my hands on this issue , can you please assign it to me

**Comment by pankajkumarbij** [comment]
@srk224 are you working on it?

Are you able to solve this issue?

**Comment by srk224** [comment]
@pankajkumarbij Yes I am working on this issue!

**Comment by pankajkumarbij** [comment]
@srk224 Keep it up

**Comment by pankajkumarbij** [comment]
@srk224 any update??

**Comment by srk224** [comment]
@pankajkumarbij I will be able to complete by tomorrow and ill show how the student profile builder looks definitely by tommorow.

**Comment by srk224** [comment]
@pankajkumarbij Actually i was not familiar with react , so I was learning it and side by side working on it, that's why it is taking so much of time 
really sorry for this delay

**Comment by pankajkumarbij** [comment]
@srk224 Ok but I need this work asap so please try to complete it asap.

**Comment by srk224** [comment]
@pankajkumarbij Yes sure...ill complete it asap

**Comment by pankajkumarbij** [comment]
@srk224 Any update?

**Comment by srk224** [comment]
@pankajkumarbij I am on it but its getting a bit difficult for me as I was not familiar with react at all. If you need it early I would say you can assign it to someone else who will be able to do it a bit early, or if you can give me some more time. I would be really thankful.

**Comment by srk224** [comment]
@pankajkumarbij Really sorry for all this delay

**Comment by Jassi10000-zz** [comment]
@pankajkumarbij brother , can I help @srk224 with the problems he's facing , you can divide our points and in this issue can also be solved and both can also have a good learning experience

**Comment by pankajkumarbij** [comment]
@srk224 ok you can take some more time.
@srk224 are you want to work with @Jassi10000?
@srk224 and @Jassi10000 you can both discuss somewhere and solve this issue.???

**Comment by Jassi10000-zz** [comment]
Yeah , am ready  
Waiting for @srk224 to reply
Meawhile @pankajkumarbij   Can you please assign  this issue to me as well along with @srk224

**Comment by pankajkumarbij** [comment]
> Yeah , am ready
> Waiting for @srk224 to reply
> Meawhile @pankajkumarbij Can you please assign this issue to me as well along with @srk224

@Jassi10000 wait for the reply of @srk224, after that I will assign you.

**Comment by Jassi10000-zz** [comment]
> > Yeah , am ready
> > Waiting for @srk224 to reply
> > Meawhile @pankajkumarbij Can you please assign this issue to me as well along with @srk224
> 
> @Jassi10000 wait for the reply of @srk224, after that I will assign you.

Sure brother, no issues

**Comment by srk224** [comment]
@pankajkumarbij yeas if Jassi is experienced in react! I would love to work with him as I will also get to learn and clear my doubts.

**Comment by Jassi10000-zz** [comment]
@srk224 Am not experienced with react but yeah clear with most of the things so would help you 
@pankajkumarbij Now can you please assign me as well

**Comment by pankajkumarbij** [comment]
@srk224 and @Jassi10000 both please complete this issue as soon as possible.

**Comment by Jassi10000-zz** [comment]
@srk224 On my Github Profile , you can find my Linkedln Profile link , just dm me there

**Comment by Jassi10000-zz** [comment]
> @srk224 and @Jassi10000 both please complete this issue as soon as possible.

Sure  @pankajkumarbij  , we will try to do it as soon as possible

**Comment by srk224** [comment]
@Jassi10000 can you give me your discord username id? ill add and text you

**Comment by Jassi10000** [comment]
Jassi#8109

**Comment by Jassi10000-zz** [comment]
@srk224  here's my discord username, just dm me , will connect to you soon   [ Jassi#8109  ]

**Comment by EkjotKaur** [comment]
Can I wok on this issue  @pankajkumarbij @asi309 @palashgdev @Vidit-jindal

**Comment by pankajkumarbij** [comment]
@EkjotKaur Other contributors are already working on it.
If they are not able to complete it then I will assign it to you.

**Comment by srk224** [comment]
@pankajkumarbij 
![image](https://user-images.githubusercontent.com/63584405/114171354-cca99a80-9951-11eb-90e7-80ce43f2f300.png)
should I proceed with this design?
and the input fields will be dynamic as you mentioned

**Comment by pankajkumarbij** [comment]
@srk224 Design is fine you can add background quite lite color.

I said for dynamic means a student can add any no of educations by clicking on the plus or an add education button.
You can explore some internship websites where you can add many education that you want to add like school, college, etc.

**Comment by srk224** [comment]
@pankajkumarbij 

https://user-images.githubusercontent.com/63584405/114226376-1f567700-9991-11eb-89b5-4079e97e42b9.mp4
This is the functionality I have Built....and I guess this is what you wanted for other input fields in education , skills etc.. I would add this in that too. I just wanted to show you before proceeding! And don't worry ill improve the UI of the whole page..I just wanted to show you the functionality first!!!

**Comment by pankajkumarbij** [comment]
> @pankajkumarbij
> 
> https://user-images.githubusercontent.com/63584405/114226376-1f567700-9991-11eb-89b5-4079e97e42b9.mp4
> This is the functionality I have Built....and I guess this is what you wanted for other input fields in education , skills etc.. I would add this in that too. I just wanted to show you before proceeding! And don't worry ill improve the UI of the whole page..I just wanted to show you the functionality first!!!

@srk224 Yes I want this functionality.
It is ok, you can improve UI and make this functionality for other required fields.

**Comment by Jassi10000-zz** [comment]
> > @pankajkumarbij
> > https://user-images.githubusercontent.com/63584405/114226376-1f567700-9991-11eb-89b5-4079e97e42b9.mp4
> > This is the functionality I have Built....and I guess this is what you wanted for other input fields in education , skills etc.. I would add this in that too. I just wanted to show you before proceeding! And don't worry ill improve the UI of the whole page..I just wanted to show you the functionality first!!!
> 
> @srk224 Yes I want this functionality.
> It is ok, you can improve UI and make this functionality for other required fields.

@pankajkumarbij In what terms we should change the UI , in terms of colors used or the alignment of input boxes in the form

**Comment by srk224** [comment]
> > > @pankajkumarbij
> > > https://user-images.githubusercontent.com/63584405/114226376-1f567700-9991-11eb-89b5-4079e97e42b9.mp4
> > > This is the functionality I have Built....and I guess this is what you wanted for other input fields in education , skills etc.. I would add this in that too. I just wanted to show you before proceeding! And don't worry ill improve the UI of the whole page..I just wanted to show you the functionality first!!!
> > 
> > 
> > @srk224 Yes I want this functionality.
> > It is ok, you can improve UI and make this functionality for other required fields.
> 
> @pankajkumarbij In what terms we should change the UI , in terms of colors used or the alignment of input boxes in the form

I will do it! I have the idea in my mind

**Comment by srk224** [comment]
@pankajkumarbij 

https://user-images.githubusercontent.com/63584405/114450090-34324500-9bf3-11eb-9d01-fc0f887961ed.mp4

I have completed it. You can take a look and tell if you have any changes. The UI also looks good and it matches with all the other pages too.!
and **can you please unassign @Jassi10000 as I didn't needed any help from him and I did everything on my own.**

**Comment by pankajkumarbij** [comment]
@srk224 Yeah  Nice Work.
Please make the education also dynamic + and - Buttons.

**Comment by pankajkumarbij** [comment]
@srk224 Check what fields required for the education that all types of education he/she can enter.

**Comment by srk224** [comment]
@pankajkumarbij  okay! Ill make the education part also dynamic.
Ill see from the linkedIn (education part) to get an idea of what input fields are required.

**Comment by pankajkumarbij** [comment]
> @pankajkumarbij okay! Ill make the education part also dynamic.
> Ill see from the linkedIn (education part) to get an idea of what input fields are required.

@srk224 
ok

**Comment by srk224** [comment]
@pankajkumarbij  I have made the education part dynamic.
what should I do next?
Should I create a PR?

**Comment by pankajkumarbij** [comment]
ok you can make a PR.

**Comment by srk224** [comment]
@pankajkumarbij I have created the PR. You can take a look

**Comment by pankajkumarbij** [comment]
@Jassi10000 please comment on below the PR so I can able to assign you.

**Comment by srk224** [comment]
@pankajkumarbij But I did all the work ! he didnt
I should get the gssoc points for this

**Comment by pankajkumarbij** [comment]
> @pankajkumarbij But I did all the work ! he didnt
> I should get the gssoc points for this

ok ok, I am unassigning him.

**Comment by Jassi10000-zz** [comment]
@srk224  Why are you soo panicking , you can take all the points not a big deal , I was only to guide you , but due to high fever from last few days , I was not able to contact you 

Anyways am glad you yourself achieved that , good luck boy , keep doing good stuff 😊

**Comment by Jassi10000-zz** [comment]
> @Jassi10000 please comment on below the PR so I can able to assign you.

Thanks @pankajkumarbij  for asking me out for this , 
but I was not able to connect with @srk224 due to my weak health ,  anyways you can unassign me and give him the required points

**Comment by srk224** [comment]
> @srk224 Why are you soo panicking , you can take all the points not a big deal , I was only to guide you , but due to high fever from last few days , I was not able to contact you
> 
> Anyways am glad you yourself achieved that , good luck boy , keep doing good stuff 😊

@Jassi10000 Oh I am sorry! Take care of yourself and get well soon ! Thanks a lot for your kind wishes.
